Route	Location	URL	Avg Stars	Your Stars	Route Type	Rating	Pitches	Length	Area Latitude	Area Longitude
Hawaii 5-O	Waimea > *Rumney > New Hampshire	https://www.mountainproject.com/route/107190755/hawaii-5-o	1.9	-1	Trad	5	1		43.80386	-71.84091
Original Tsunami	Waimea > *Rumney > New Hampshire	https://www.mountainproject.com/route/107710181/original-tsunami	4	-1	"Trad, Aid"	5.6 A3-4 R	1	50	43.80386	-71.84091
That Crack	Waimea > *Rumney > New Hampshire	https://www.mountainproject.com/route/106005291/that-crack	2.3	-1	Trad	5.10a	1		43.80386	-71.84091
Waimea The Weenie Way	Waimea > *Rumney > New Hampshire	https://www.mountainproject.com/route/105962302/waimea-the-weenie-way	1.9	-1	Trad	5.10c	1		43.80386	-71.84091
Waimea	Waimea > *Rumney > New Hampshire	https://www.mountainproject.com/route/105867858/waimea	3.6	-1	Sport	5.10d	1	50	43.80386	-71.84091
Long Board	Waimea > *Rumney > New Hampshire	https://www.mountainproject.com/route/105927776/long-board	1.9	-1	Sport	5.10d	1		43.80386	-71.84091
Surf's Up	Waimea > *Rumney > New Hampshire	https://www.mountainproject.com/route/106271785/surfs-up	1.7	-1	Trad	5.10d R	1	50	43.80386	-71.84091
All the Way-A	Waimea > *Rumney > New Hampshire	https://www.mountainproject.com/route/105944400/all-the-way-a	2.7	-1	Sport	5.11a	1	40	43.80386	-71.84091
Flying Hawaiian	Waimea > *Rumney > New Hampshire	https://www.mountainproject.com/route/105910536/flying-hawaiian	3.8	-1	Sport	5.11b	1		43.80386	-71.84091
Short Board	Waimea > *Rumney > New Hampshire	https://www.mountainproject.com/route/106520925/short-board	1.8	-1	Sport	5.11b	1	25	43.80386	-71.84091
Vantage Point	Waimea > *Rumney > New Hampshire	https://www.mountainproject.com/route/107184968/vantage-point	2	-1	TR	5.11	1	45	43.80386	-71.84091
Spiny Dogfish	Waimea > *Rumney > New Hampshire	https://www.mountainproject.com/route/107185001/spiny-dogfish	2.7	-1	TR	5.11c	1		43.80386	-71.84091
Groupie Fantasy	Waimea > *Rumney > New Hampshire	https://www.mountainproject.com/route/106041632/groupie-fantasy	2.7	-1	Sport	5.11c	1		43.80386	-71.84091
Bonzai Pipeline	Waimea > *Rumney > New Hampshire	https://www.mountainproject.com/route/111129757/bonzai-pipeline	3.5	-1	Trad	5.11+	1	35	43.80386	-71.84091
Supersize Me	Main Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/106059019/supersize-me	1.6	-1	Sport	5.6	1	30	43.8025	-71.83593
Fear of Abraham	Main Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/106098583/fear-of-abraham	1.8	-1	Trad	5.6	1		43.8025	-71.83593
Fat Man	Main Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/106058997/fat-man	1.8	-1	Sport	5.7	1	30	43.8025	-71.83593
Working Man	Main Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/109718367/working-man	1.7	-1	"Trad, TR"	5.7	1	40	43.8025	-71.83593
Rock de Jours	Main Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/106236801/rock-de-jours	2.4	-1	Trad	5.8 X	3	200	43.8025	-71.83593
Gold Digger	Main Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/105927100/gold-digger	2.3	-1	Sport	5.8+	1		43.8025	-71.83593
Sky Lab (incomplete)	Main Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/106521100/sky-lab-incomplete	2	-1	"Trad, Aid"	5.9 A3 R	1	80	43.8025	-71.83593
Rock Du Jours Direct	Main Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/106028627/rock-du-jours-direct	3	-1	Sport	5.9+	2	180	43.8025	-71.83593
Space Shuttle	Main Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/106098427/space-shuttle	3	-1	Trad	5.9+	1		43.8025	-71.83593
Underdog	Main Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/105877217/underdog	3.4	-1	Sport	5.10a	1		43.8025	-71.83593
Sweet Polly Purebred	Main Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/105877209/sweet-polly-purebred	3.1	-1	Sport	5.10c	1		43.8025	-71.83593
Millenium Falcon	Main Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/106021168/millenium-falcon	3.6	-1	Sport	5.10c	1	75	43.8025	-71.83593
The Thang	Main Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/108234515/the-thang	2.1	-1	Sport	5.10c	1		43.8025	-71.83593
The Thing	Main Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/108277569/the-thing	1.8	-1	Sport	5.10d	1		43.8025	-71.83593
Goldbug	Main Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/105963695/goldbug	2.6	-1	Sport	5.10d	1		43.8025	-71.83593
Know Ethics	Main Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/105877243/know-ethics	3.1	-1	Sport	5.11a	1		43.8025	-71.83593
Little Big Man	Main Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/105927113/little-big-man	2.1	-1	Sport	5.11b	1		43.8025	-71.83593
Gunboat Diplomacy	Main Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/105896036/gunboat-diplomacy	2.7	-1	Sport	5.11b/c	1	75	43.8025	-71.83593
Ali Babbler	Main Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/105927124/ali-babbler	2.6	-1	Sport	5.11c	1		43.8025	-71.83593
Iron Man	Main Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/105961435/iron-man	2.8	-1	Sport	5.11c	1		43.8025	-71.83593
Via Ferrata	Main Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/105991298/via-ferrata	3.1	-1	Sport	5.11c	3	200	43.8025	-71.83593
Shiskebob	Main Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/106924270/shiskebob	2.3	-1	Trad	5.11c PG13	1		43.8025	-71.83593
Standard Route	Jimmy Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/106397749/standard-route	1.4	-1	Trad	5.3	2	300	43.80417	-71.84037
The Searchers	Jimmy Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/106830878/the-searchers	1.8	-1	Trad	5.3 R	2	300	43.80417	-71.84037
Clip a Dee Doo Dah	Jimmy Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/105888037/clip-a-dee-doo-dah	3.1	-1	Sport	5.3	2	300	43.80417	-71.84037
Pine Tree Crack	Jimmy Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/106057097/pine-tree-crack	2.5	-1	Trad	5.4	2	250	43.80417	-71.84037
Lady and the Tramp	Jimmy Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/106057108/lady-and-the-tramp	2.6	-1	Sport	5.4	2	250	43.80417	-71.84037
Stool Pigeon	Jimmy Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/106855478/stool-pigeon	0.7	-1	Trad	5.4 R	1	100	43.80417	-71.84037
Piece of Cake	Jimmy Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/106491699/piece-of-cake	2	-1	Sport	5.5	1	50	43.80417	-71.84037
Cracker Cracks	Jimmy Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/106927911/cracker-cracks	0	-1	Trad	5.5 PG13	1	50	43.80417	-71.84037
Scare Crow	Jimmy Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/107513988/scare-crow	1.3	-1	Trad	5.5 PG13	1	100	43.80417	-71.84037
Alcove Crack	Jimmy Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/106075767/alcove-crack	1.7	-1	Trad	5.5	1		43.80417	-71.84037
Things You Should Have Learned in Kindergarten	Jimmy Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/105925163/things-you-should-have-learned-in-kindergarten	1.9	-1	Sport	5.6	1		43.80417	-71.84037
When Pigs Fly	Jimmy Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/106865476/when-pigs-fly	1.3	-1	Trad	5.6 R	1	100	43.80417	-71.84037
Jimmy Crack Corn	Jimmy Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/106892515/jimmy-crack-corn	0.5	-1	Trad	5.6 R	4	200	43.80417	-71.84037
The Nuthatch	Jimmy Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/105917818/the-nuthatch	2.4	-1	Sport	5.7	1		43.80417	-71.84037
Teacher's Pet	Jimmy Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/105925169/teachers-pet	1.7	-1	Sport	5.7	1		43.80417	-71.84037
Drilling for Dollars	Jimmy Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/105878341/drilling-for-dollars	2	-1	Sport	5.8	1		43.80417	-71.84037
Junco	Jimmy Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/105876683/junco	3.3	-1	Sport	5.8+	1	80	43.80417	-71.84037
Things I Never Learned	Jimmy Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/105925175/things-i-never-learned	2.2	-1	Sport	5.9	1		43.80417	-71.84037
"To Love, Honor and Belay"	Jimmy Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/106276559/to-love-honor-and-belay	2	-1	Sport	5.9	1		43.80417	-71.84037
Love Nest	Jimmy Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/106499000/love-nest	1.4	-1	"Trad, TR"	5.9	1		43.80417	-71.84037
Lonesome Dove	Jimmy Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/105879126/lonesome-dove	3.6	-1	Sport	5.10a	1		43.80417	-71.84037
The Beginning of All Things	Jimmy Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/105986139/the-beginning-of-all-things	1.6	-1	Sport	5.10a	1		43.80417	-71.84037
Easter Squall	Jimmy Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/106075680/easter-squall	2	-1	Sport	5.10b	1	40	43.80417	-71.84037
Things as They Are	Jimmy Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/105925179/things-as-they-are	2.4	-1	Sport	5.10c	1		43.80417	-71.84037
Hammond Organ	Jimmy Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/105917803/hammond-organ	2.7	-1	Sport	5.10c/d	1		43.80417	-71.84037
Hypocrisy	Jimmy Cliff > *Rumney > New Hampshire	https://www.mountainproject.com/route/106491820/hypocrisy	1.9	-1	Sport	5.10d	1		43.80417	-71.84037
Five Steps	Bonsai > *Rumney > New Hampshire	https://www.mountainproject.com/route/106302944/five-steps	1.4	-1	Trad	5.4	1	50	43.80288	-71.83926
The Flake	Bonsai > *Rumney > New Hampshire	https://www.mountainproject.com/route/106302794/the-flake	1.3	-1	Trad	5.5	1	40	43.80288	-71.83926
Kamikazee	Bonsai > *Rumney > New Hampshire	https://www.mountainproject.com/route/105939289/kamikazee	1.2	-1	Sport	5.8	1		43.80288	-71.83926
Bombs Away	Bonsai > *Rumney > New Hampshire	https://www.mountainproject.com/route/106302809/bombs-away	2	-1	Trad	5.8+ PG13	1	90	43.80288	-71.83926
War and  Peace	Bonsai > *Rumney > New Hampshire	https://www.mountainproject.com/route/105878619/war-and-peace	2.7	-1	Sport	5.9+	1		43.80288	-71.83926
Masterpiece	Bonsai > *Rumney > New Hampshire	https://www.mountainproject.com/route/105878204/masterpiece	3.1	-1	Sport	5.10a	1		43.80288	-71.83926
Jugline	Bonsai > *Rumney > New Hampshire	https://www.mountainproject.com/route/106014669/jugline	2.3	-1	Sport	5.10b	1		43.80288	-71.83926
Social Obligation	Bonsai > *Rumney > New Hampshire	https://www.mountainproject.com/route/106014674/social-obligation	1.9	-1	Sport	5.10c	1		43.80288	-71.83926
Centerpiece	Bonsai > *Rumney > New Hampshire	https://www.mountainproject.com/route/105906870/centerpiece	3.3	-1	Sport	5.10d	1	70	43.80288	-71.83926
Peer Pressure	Bonsai > *Rumney > New Hampshire	https://www.mountainproject.com/route/105927987/peer-pressure	3.5	-1	Sport	5.10d	1		43.80288	-71.83926
Anti-Social Behavior	Bonsai > *Rumney > New Hampshire	https://www.mountainproject.com/route/105956683/anti-social-behavior	2.2	-1	Sport	5.11b	1	35	43.80288	-71.83926
Social Climber	Bonsai > *Rumney > New Hampshire	https://www.mountainproject.com/route/105964233/social-climber	2.6	-1	Trad	5.11b	1		43.80288	-71.83926
Bonsai Bulge	Bonsai > *Rumney > New Hampshire	https://www.mountainproject.com/route/106016899/bonsai-bulge	1.8	-1	Sport	5.11c	1		43.80288	-71.83926
Cavatelli	Bonsai > *Rumney > New Hampshire	https://www.mountainproject.com/route/106271806/cavatelli	2	-1	Sport	5.11c	1		43.80288	-71.83926
Dirtigo	Venus Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/105932987/dirtigo	2.4	-1	Sport	5.3	1		43.80188	-71.8375
The Wimpy -Gilman Ridge	Venus Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/105932996/the-wimpy-gilman-ridge	2.6	-1	Sport	5.3	1		43.80188	-71.8375
Mowgli Grape	Venus Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/105933024/mowgli-grape	2.2	-1	Sport	5.3	1		43.80188	-71.8375
Mountaineer's Crack	Venus Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/106738518/mountaineers-crack	0.5	-1	Trad	5.4	1		43.80188	-71.8375
Screamin'	Venus Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/111151386/screamin	1	-1	Trad	5.7 R	1	85	43.80188	-71.8375
Preppy's Crack	Venus Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/105933001/preppys-crack	2.1	-1	Sport	5.7	1		43.80188	-71.8375
Constipation Prize	Venus Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/105933013/constipation-prize	2	-1	Sport	5.8	1		43.80188	-71.8375
Venus Envy	Venus Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/105932968/venus-envy	2.1	-1	Sport	5.10a	1		43.80188	-71.8375
Granny's Route	5.8 Crag > *Rumney > New Hampshire	https://www.mountainproject.com/route/106334928/grannys-route	1.3	-1	Sport	5.4	1	45	43.80105	-71.83823
The 5.8 Crack by the Road	5.8 Crag > *Rumney > New Hampshire	https://www.mountainproject.com/route/105906994/the-58-crack-by-the-road	2.5	-1	Trad	5.7	1		43.80105	-71.83823
Chimney of Doom	5.8 Crag > *Rumney > New Hampshire	https://www.mountainproject.com/route/105911730/chimney-of-doom	1.8	-1	Trad	5.7	1		43.80105	-71.83823
Asbury Park	5.8 Crag > *Rumney > New Hampshire	https://www.mountainproject.com/route/105922314/asbury-park	1.8	-1	Sport	5.7	1		43.80105	-71.83823
The Terrace	5.8 Crag > *Rumney > New Hampshire	https://www.mountainproject.com/route/105878180/the-terrace	1.3	-1	Sport	5.8	1	30	43.80105	-71.83823
Snake Skin Slab	5.8 Crag > *Rumney > New Hampshire	https://www.mountainproject.com/route/105923846/snake-skin-slab	2.3	-1	Sport	5.8	1		43.80105	-71.83823
Raven	5.8 Crag > *Rumney > New Hampshire	https://www.mountainproject.com/route/105924554/raven	1.7	-1	Sport	5.8	1		43.80105	-71.83823
Moe Pup Sensation	5.8 Crag > *Rumney > New Hampshire	https://www.mountainproject.com/route/106743156/moe-pup-sensation	2	-1	Sport	5.8	1		43.80105	-71.83823
Bolt And Run	5.8 Crag > *Rumney > New Hampshire	https://www.mountainproject.com/route/105922323/bolt-and-run	2.3	-1	Sport	5.9	1		43.80105	-71.83823
Central Park	5.8 Crag > *Rumney > New Hampshire	https://www.mountainproject.com/route/106478452/central-park	1.7	-1	TR	5.9+	1	45	43.80105	-71.83823
Romancing The Snake	5.8 Crag > *Rumney > New Hampshire	https://www.mountainproject.com/route/106091432/romancing-the-snake	2.1	-1	Trad	5.10b/c	1		43.80105	-71.83823
Romancing the Stone	5.8 Crag > *Rumney > New Hampshire	https://www.mountainproject.com/route/105878174/romancing-the-stone	2.9	-1	Sport	5.10c	1	60	43.80105	-71.83823
Only a Crow	5.8 Crag > *Rumney > New Hampshire	https://www.mountainproject.com/route/105929478/only-a-crow	1.8	-1	Sport	5.10c	1		43.80105	-71.83823
Milksnake	5.8 Crag > *Rumney > New Hampshire	https://www.mountainproject.com/route/106091425/milksnake	1.7	-1	Trad	5.10c	1		43.80105	-71.83823
Blue Spotted Tail	5.8 Crag > *Rumney > New Hampshire	https://www.mountainproject.com/route/107473478/blue-spotted-tail	1.4	-1	TR	5.10+	1	40	43.80105	-71.83823
Milktoast	5.8 Crag > *Rumney > New Hampshire	https://www.mountainproject.com/route/106089724/milktoast	2.2	-1	Sport	5.10c/d	1		43.80105	-71.83823
License to Ill	5.8 Crag > *Rumney > New Hampshire	https://www.mountainproject.com/route/105925586/license-to-ill	2.7	-1	Trad	5.11a R	1		43.80105	-71.83823
Sky Pilot	5.8 Crag > *Rumney > New Hampshire	https://www.mountainproject.com/route/105878810/sky-pilot	2.7	-1	Sport	5.11b	1		43.80105	-71.83823
Blueballs at Christmas	5.8 Crag > *Rumney > New Hampshire	https://www.mountainproject.com/route/105935056/blueballs-at-christmas	2.4	-1	Trad	5.11b R	1		43.80105	-71.83823
Arm and Hammer	5.8 Crag > *Rumney > New Hampshire	https://www.mountainproject.com/route/105878804/arm-and-hammer	2.5	-1	Sport	5.11c	1		43.80105	-71.83823
The Sand People	Darth Vader > *Rumney > New Hampshire	https://www.mountainproject.com/route/105917400/the-sand-people	2.1	-1	Sport	5.8+	1		43.80352	-71.8404
Yoda	Darth Vader > *Rumney > New Hampshire	https://www.mountainproject.com/route/105906879/yoda	3	-1	Sport	5.9	1		43.80352	-71.8404
Darth Vader	Darth Vader > *Rumney > New Hampshire	https://www.mountainproject.com/route/105917376/darth-vader	2.5	-1	Trad	5.9	1		43.80352	-71.8404
Oby-won Ryobi	Darth Vader > *Rumney > New Hampshire	https://www.mountainproject.com/route/105906887/oby-won-ryobi	3.1	-1	Sport	5.9+	1		43.80352	-71.8404
The Prawn	Darth Vader > *Rumney > New Hampshire	https://www.mountainproject.com/route/106036805/the-prawn	1.6	-1	Sport	5.10c	1	30	43.80352	-71.8404
Orange Sunshine	Orange Crush > *Rumney > New Hampshire	https://www.mountainproject.com/route/106012914/orange-sunshine	2.6	-1	Sport	5.6	1	100	43.80293	-71.83513
The Original Orange Crush	Orange Crush > *Rumney > New Hampshire	https://www.mountainproject.com/route/106495191/the-original-orange-crush	2	-1	Trad	5.8 R	3	150	43.80293	-71.83513
Orange Crush (retro-bolted)	Orange Crush > *Rumney > New Hampshire	https://www.mountainproject.com/route/106775797/orange-crush-retro-bolted	2.3	-1	Sport	5.9	1	50	43.80293	-71.83513
Purple Microdot	Orange Crush > *Rumney > New Hampshire	https://www.mountainproject.com/route/106033480/purple-microdot	1.9	-1	Sport	5.10b	1		43.80293	-71.83513
Chinese Water Torture	Orange Crush > *Rumney > New Hampshire	https://www.mountainproject.com/route/106495271/chinese-water-torture	2.7	-1	Sport	5.1	1	150	43.80293	-71.83513
Citrasolve	Orange Crush > *Rumney > New Hampshire	https://www.mountainproject.com/route/106598700/citrasolve	2.3	-1	Sport	5.10c	1	50	43.80293	-71.83513
Tropicana	Orange Crush > *Rumney > New Hampshire	https://www.mountainproject.com/route/105884809/tropicana	3.5	-1	Sport	5.11a	2		43.80293	-71.83513
Sir Edmond Drillary	Orange Crush > *Rumney > New Hampshire	https://www.mountainproject.com/route/105968581/sir-edmond-drillary	1.4	-1	Sport	5.11a	1		43.80293	-71.83513
Prime Climb	Orange Crush > *Rumney > New Hampshire	https://www.mountainproject.com/route/106012937/prime-climb	2.7	-1	Sport	5.11b	1		43.80293	-71.83513
Buried Treasure	Orange Crush > *Rumney > New Hampshire	https://www.mountainproject.com/route/106013257/buried-treasure	3.1	-1	Sport	5.11b	1	80	43.80293	-71.83513
Lions and Tigers and Bears	Orange Crush > *Rumney > New Hampshire	https://www.mountainproject.com/route/106033484/lions-and-tigers-and-bears	3.2	-1	Sport	5.11b	1		43.80293	-71.83513
Oh My! finish	Orange Crush > *Rumney > New Hampshire	https://www.mountainproject.com/route/106033489/oh-my-finish	3.5	-1	Sport	5.11b/c	1		43.80293	-71.83513
Black Mamba	Orange Crush > *Rumney > New Hampshire	https://www.mountainproject.com/route/105996485/black-mamba	3.5	-1	Sport	5.11c	1	60	43.80293	-71.83513
The Drillary Step	Orange Crush > *Rumney > New Hampshire	https://www.mountainproject.com/route/106043129/the-drillary-step	2	-1	Sport	5.11c	1	30	43.80293	-71.83513
The Crusher	Orange Crush > *Rumney > New Hampshire	https://www.mountainproject.com/route/106200868/the-crusher	3.8	-1	Sport	5.11d	1	80	43.80293	-71.83513
Today Morning	New Wave > *Rumney > New Hampshire	https://www.mountainproject.com/route/117597961/today-morning	2	-1	Sport	5.6	1	65	43.80285	-71.83444
Schist Another Crack	New Wave > *Rumney > New Hampshire	https://www.mountainproject.com/route/111123218/schist-another-crack	1.2	-1	Trad	5.7	1	45	43.80285	-71.83444
Air and Pleasant Danger	New Wave > *Rumney > New Hampshire	https://www.mountainproject.com/route/105925159/air-and-pleasant-danger	2.3	-1	Sport	5.8	1	70	43.80285	-71.83444
Schist Another Sport Climb	New Wave > *Rumney > New Hampshire	https://www.mountainproject.com/route/106600975/schist-another-sport-climb	1.7	-1	Sport	5.8+	1	40	43.80285	-71.83444
The Daytripper	New Wave > *Rumney > New Hampshire	https://www.mountainproject.com/route/106793303/the-daytripper	1.9	-1	Sport	5.8+	1	50	43.80285	-71.83444
Night Crawler	New Wave > *Rumney > New Hampshire	https://www.mountainproject.com/route/106793287/night-crawler	2.1	-1	Sport	5.9	1	40	43.80285	-71.83444
Smokestack	New Wave > *Rumney > New Hampshire	https://www.mountainproject.com/route/105998986/smokestack	3.4	-1	Sport	5.9+	1		43.80285	-71.83444
Black Dog Crack	New Wave > *Rumney > New Hampshire	https://www.mountainproject.com/route/106003101/black-dog-crack	2.4	-1	Sport	5.10b	1		43.80285	-71.83444
Ten of Spades	New Wave > *Rumney > New Hampshire	https://www.mountainproject.com/route/105968891/ten-of-spades	2.7	-1	Sport	5.10c	1		43.80285	-71.83444
Short Wave	New Wave > *Rumney > New Hampshire	https://www.mountainproject.com/route/105959853/short-wave	2	-1	Sport	5.11b	1		43.80285	-71.83444
Sam Spade	New Wave > *Rumney > New Hampshire	https://www.mountainproject.com/route/106505322/sam-spade	2.3	-1	Trad	5.11	1	80	43.80285	-71.83444
Barking Spiders	New Wave > *Rumney > New Hampshire	https://www.mountainproject.com/route/106166465/barking-spiders	2.5	-1	Sport	5.11c	1		43.80285	-71.83444
Salley's Alley	New Wave > *Rumney > New Hampshire	https://www.mountainproject.com/route/105896493/salleys-alley	3	-1	Sport	5.11c	1	50	43.80285	-71.83444
Retrospade	New Wave > *Rumney > New Hampshire	https://www.mountainproject.com/route/106066661/retrospade	3.2	-1	Sport	5.11c/d	1	70	43.80285	-71.83444
A Week With Pete	The Parking Lot Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/105956196/a-week-with-pete	2.2	-1	Sport	5.3	1	55	43.80273	-71.83029
Centerfold	The Parking Lot Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/106071424/centerfold	0.7	-1	Trad	5.4	1		43.80273	-71.83029
Glory Jean's	The Parking Lot Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/105961422/glory-jeans	2.6	-1	Sport	5.6	1	40	43.80273	-71.83029
Cafe au Lait	The Parking Lot Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/106009336/cafe-au-lait	2.3	-1	Sport	5.6	1		43.80273	-71.83029
Shealyn's Way	The Parking Lot Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/105962298/shealyns-way	2.9	-1	Sport	5.7	1		43.80273	-71.83029
Rise and Shine	The Parking Lot Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/105962922/rise-and-shine	2.4	-1	Sport	5.7	1		43.80273	-71.83029
Easily Amused	The Parking Lot Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/105966659/easily-amused	1.7	-1	Sport	5.7	1		43.80273	-71.83029
Percolator	The Parking Lot Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/106009347/percolator	1.2	-1	Sport	5.7	1		43.80273	-71.83029
Dead Sea Equestrian	The Parking Lot Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/106071441/dead-sea-equestrian	2.1	-1	Sport	5.7	1		43.80273	-71.83029
Chloe's Breakfast Special	The Parking Lot Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/105900343/chloes-breakfast-special	2.5	-1	Sport	5.8	1	70	43.80273	-71.83029
Squeeze My Lemon	The Parking Lot Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/106071435/squeeze-my-lemon	2.3	-1	Sport	5.8	1		43.80273	-71.83029
Shemp Lives	The Parking Lot Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/106391407/shemp-lives	1.8	-1	Sport	5.8	1	50	43.80273	-71.83029
Curly for President	The Parking Lot Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/106254868/curly-for-president	2.7	-1	Sport	5.9-	1		43.80273	-71.83029
Quinn/Callaghan	The Parking Lot Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/106263795/quinncallaghan	2.4	-1	Sport	5.9-	1	80	43.80273	-71.83029
Easily Aroused	The Parking Lot Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/105971474/easily-aroused	1.7	-1	Sport	5.9	1		43.80273	-71.83029
Egg McMeadows	The Parking Lot Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/105962933/egg-mcmeadows	2.3	-1	Sport	5.9+	1		43.80273	-71.83029
Red Sea Pedestrian	The Parking Lot Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/105956200/red-sea-pedestrian	2.2	-1	Sport	5.10b	1	45	43.80273	-71.83029
Juan Valdez	The Parking Lot Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/105962294/juan-valdez	2.5	-1	Sport	5.10b	1		43.80273	-71.83029
Rubicon	The Parking Lot Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/106573480/rubicon	2	-1	Sport	5.10b/c	1	40	43.80273	-71.83029
Idiot's Deluxe	The Parking Lot Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/106254851/idiots-deluxe	2.8	-1	Sport	5.10c/d	1		43.80273	-71.83029
Espresso	The Parking Lot Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/105898433/espresso	3.1	-1	Sport	5.10d	1	60	43.80273	-71.83029
Mr. Coffee	The Parking Lot Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/106009341/mr-coffee	1.2	-1	Sport	5.11a	1		43.80273	-71.83029
100% Columbian	The Parking Lot Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/105962286/100-columbian	2.9	-1	Sport	5.11c	1		43.80273	-71.83029
Cranky Pants	The Prudential > *Rumney > New Hampshire	https://www.mountainproject.com/route/113689790/cranky-pants	1.5	-1	Sport	5.5	1		43.80513	-71.84452
Bright Eyes	The Prudential > *Rumney > New Hampshire	https://www.mountainproject.com/route/114486350/bright-eyes	2.5	-1	Sport	5.5	1	45	43.80513	-71.84452
Blue Sky and Rhino Horns	The Prudential > *Rumney > New Hampshire	https://www.mountainproject.com/route/112093818/blue-sky-and-rhino-horns	2	-1	Sport	5.8	1	60	43.80513	-71.84452
Prudential Crack's Finish (unfinished)	The Prudential > *Rumney > New Hampshire	https://www.mountainproject.com/route/106856719/prudential-cracks-finish-unfinished	1	-1	"Trad, Aid"	5.8 A3 PG13	1	50	43.80513	-71.84452
Prudential Crack	The Prudential > *Rumney > New Hampshire	https://www.mountainproject.com/route/110180499/prudential-crack	1.7	-1	Trad	5.8+	1	25	43.80513	-71.84452
Tumbling Dice	The Prudential > *Rumney > New Hampshire	https://www.mountainproject.com/route/117387231/tumbling-dice	2	-1	Sport	5.9-	1	75	43.80513	-71.84452
"Ugly Crack (aka, sandbag crack)"	The Prudential > *Rumney > New Hampshire	https://www.mountainproject.com/route/107387698/ugly-crack-aka-sandbag-crack	0.5	-1	Trad	5.9	1	45	43.80513	-71.84452
Nice Land	The Prudential > *Rumney > New Hampshire	https://www.mountainproject.com/route/105970601/nice-land	2.3	-1	Sport	5.10b	1		43.80513	-71.84452
El Funko	The Prudential > *Rumney > New Hampshire	https://www.mountainproject.com/route/106036835/el-funko	2.3	-1	Sport	5.10b	1		43.80513	-71.84452
Swedish Girls	The Prudential > *Rumney > New Hampshire	https://www.mountainproject.com/route/105970612/swedish-girls	2.5	-1	Sport	5.10d	1		43.80513	-71.84452
Short and sharp	The Prudential > *Rumney > New Hampshire	https://www.mountainproject.com/route/106975578/short-and-sharp	0.9	-1	Sport	5.11a	1	40	43.80513	-71.84452
Prudential Off-Width (LYLALTI start)	The Prudential > *Rumney > New Hampshire	https://www.mountainproject.com/route/114111381/prudential-off-width-lylalti-start	2	-1	Trad	5.11a	1	35	43.80513	-71.84452
Finland	The Prudential > *Rumney > New Hampshire	https://www.mountainproject.com/route/106036846/finland	2.8	-1	Sport	5.11b	1		43.80513	-71.84452
Measured Doses	The Prudential > *Rumney > New Hampshire	https://www.mountainproject.com/route/107097013/measured-doses	0.6	-1	Sport	5.11b	1	40	43.80513	-71.84452
Midget Tricks	The Prudential > *Rumney > New Hampshire	https://www.mountainproject.com/route/106837931/midget-tricks	0.5	-1	Sport	5.11c	1	25	43.80513	-71.84452
Soft Machine	The Prudential > *Rumney > New Hampshire	https://www.mountainproject.com/route/105970594/soft-machine	2.4	-1	Sport	5.11c	1		43.80513	-71.84452
Machine Head	The Prudential > *Rumney > New Hampshire	https://www.mountainproject.com/route/105907696/machine-head	3	-1	Sport	5.11d	1		43.80513	-71.84452
Hard Drive	The Prudential > *Rumney > New Hampshire	https://www.mountainproject.com/route/108061203/hard-drive	2	-1	Sport	5.11d	1	60	43.80513	-71.84452
Rose Garden	No Money Down (Left) > The Meadows > *Rumney > New Hampshire	https://www.mountainproject.com/route/105923573/rose-garden	1.8	-1	Sport	5.7	1	45	43.8023	-71.83202
False Modesty	No Money Down (Left) > The Meadows > *Rumney > New Hampshire	https://www.mountainproject.com/route/105923651/false-modesty	2	-1	Sport	5.7	1	45	43.8023	-71.83202
Truth in Advertising	No Money Down (Left) > The Meadows > *Rumney > New Hampshire	https://www.mountainproject.com/route/105923587/truth-in-advertising	1.9	-1	Sport	5.7+	1	45	43.8023	-71.83202
Easy Terms	No Money Down (Left) > The Meadows > *Rumney > New Hampshire	https://www.mountainproject.com/route/105923640/easy-terms	2	-1	Sport	5.8	1	45	43.8023	-71.83202
Dung Beetle	No Money Down (Left) > The Meadows > *Rumney > New Hampshire	https://www.mountainproject.com/route/106057661/dung-beetle	1.9	-1	Sport	5.8+	1		43.8023	-71.83202
Thou Shalt Not Covet	No Money Down (Left) > The Meadows > *Rumney > New Hampshire	https://www.mountainproject.com/route/105962344/thou-shalt-not-covet	2	-1	Sport	5.9	1		43.8023	-71.83202
Mr. Popular	No Money Down (Left) > The Meadows > *Rumney > New Hampshire	https://www.mountainproject.com/route/105961395/mr-popular	1.8	-1	Sport	5.10a	1		43.8023	-71.83202
Repossession	No Money Down (Left) > The Meadows > *Rumney > New Hampshire	https://www.mountainproject.com/route/106057598/repossession	1.6	-1	Sport	5.10a	1		43.8023	-71.83202
No Money Down	No Money Down (Left) > The Meadows > *Rumney > New Hampshire	https://www.mountainproject.com/route/105908656/no-money-down	2.7	-1	Sport	5.10c	1		43.8023	-71.83202
Student Loan	No Money Down (Left) > The Meadows > *Rumney > New Hampshire	https://www.mountainproject.com/route/105962327/student-loan	2.2	-1	Sport	5.11b	1		43.8023	-71.83202
The Coveted	No Money Down (Left) > The Meadows > *Rumney > New Hampshire	https://www.mountainproject.com/route/106784670/the-coveted	1.4	-1	Trad	5.11b	1	30	43.8023	-71.83202
Beginner's Route	Center Section > The Meadows > *Rumney > New Hampshire	https://www.mountainproject.com/route/105908648/beginners-route	2.6	-1	Trad	5.5	1		43.80231	-71.83173
Mom's Pancake	Center Section > The Meadows > *Rumney > New Hampshire	https://www.mountainproject.com/route/106057691/moms-pancake	2.1	-1	Sport	5.5	1		43.80231	-71.83173
Bolt Line	Center Section > The Meadows > *Rumney > New Hampshire	https://www.mountainproject.com/route/105923805/bolt-line	2.5	-1	Sport	5.8	1	70	43.80231	-71.83173
Lies and Propaganda	Center Section > The Meadows > *Rumney > New Hampshire	https://www.mountainproject.com/route/105923839/lies-and-propaganda	2.6	-1	Sport	5.9	1	55	43.80231	-71.83173
Hippos on Parade	Center Section > The Meadows > *Rumney > New Hampshire	https://www.mountainproject.com/route/105961400/hippos-on-parade	2.7	-1	Sport	5.9	1		43.80231	-71.83173
Tunnel Zone	Center Section > The Meadows > *Rumney > New Hampshire	https://www.mountainproject.com/route/106409759/tunnel-zone	1.5	-1	Trad	5.9	1		43.80231	-71.83173
Rhino Bucket	Center Section > The Meadows > *Rumney > New Hampshire	https://www.mountainproject.com/route/105961410/rhino-bucket	2.4	-1	Sport	5.10a	1		43.80231	-71.83173
Misdemeanor	Center Section > The Meadows > *Rumney > New Hampshire	https://www.mountainproject.com/route/106033945/misdemeanor	3	-1	Sport	5.10b	1	85	43.80231	-71.83173
Med Dose Madness	Center Section > The Meadows > *Rumney > New Hampshire	https://www.mountainproject.com/route/106221466/med-dose-madness	1.9	-1	Sport	5.10b PG13	1		43.80231	-71.83173
Bonehead Roof	Center Section > The Meadows > *Rumney > New Hampshire	https://www.mountainproject.com/route/105923973/bonehead-roof	1.5	-1	Sport	5.10c	1		43.80231	-71.83173
Cold Turkey	Center Section > The Meadows > *Rumney > New Hampshire	https://www.mountainproject.com/route/105961405/cold-turkey	2.5	-1	Sport	5.10c	1		43.80231	-71.83173
Holderness School Corner	Holderness Corner > The Meadows > *Rumney > New Hampshire	https://www.mountainproject.com/route/105962946/holderness-school-corner	3	-1	Trad	5.8	1		43.8024	-71.8314
Holderness Arete	Holderness Corner > The Meadows > *Rumney > New Hampshire	https://www.mountainproject.com/route/105962956/holderness-arete	2.5	-1	Sport	5.10b	1		43.8024	-71.8314
Holderness Finish	Holderness Corner > The Meadows > *Rumney > New Hampshire	https://www.mountainproject.com/route/106071449/holderness-finish	2.1	-1	Trad	5.10b	1		43.8024	-71.8314
White Rhino	Holderness Corner > The Meadows > *Rumney > New Hampshire	https://www.mountainproject.com/route/105961415/white-rhino	2.4	-1	Sport	5.11c	1		43.8024	-71.8314
Kate's Arete	Apocalypse Walls > *Rumney > New Hampshire	https://www.mountainproject.com/route/105917773/kates-arete	1.6	-1	Sport	5.4	1		43.80231	-71.8324
They Come and They Go	Apocalypse Walls > *Rumney > New Hampshire	https://www.mountainproject.com/route/106932264/they-come-and-they-go	0.5	-1	Trad	5.6 R	2	110	43.80231	-71.8324
Serenity Now	Apocalypse Walls > *Rumney > New Hampshire	https://www.mountainproject.com/route/105908766/serenity-now	1.7	-1	Sport	5.7	1		43.80231	-71.8324
An Elephant Never Forgets	Apocalypse Walls > *Rumney > New Hampshire	https://www.mountainproject.com/route/106933160/an-elephant-never-forgets	0	-1	"Trad, Aid"	5.10 A1 PG13	1	40	43.80231	-71.8324
Supreme Onion Sacrifice	Apocalypse Walls > *Rumney > New Hampshire	https://www.mountainproject.com/route/105917766/supreme-onion-sacrifice	2.3	-1	Sport	5.11a	1		43.80231	-71.8324
Corporal Punishment	Apocalypse Walls > *Rumney > New Hampshire	https://www.mountainproject.com/route/105917784/corporal-punishment	2.2	-1	Sport	5.11b	1		43.80231	-71.8324
Captain Fingers	Apocalypse Walls > *Rumney > New Hampshire	https://www.mountainproject.com/route/105908771/captain-fingers	2.7	-1	Sport	5.11c	1		43.80231	-71.8324
Apocalypse Later	Apocalypse Walls > *Rumney > New Hampshire	https://www.mountainproject.com/route/105908757/apocalypse-later	3.5	-1	Sport	5.11d	1		43.80231	-71.8324
Old Yeller	Yellowknife Buttress > *Rumney > New Hampshire	https://www.mountainproject.com/route/107343200/old-yeller	1	-1	Trad	5.6 R	2	170	43.80532	-71.84351
Lone Wolf	Yellowknife Buttress > *Rumney > New Hampshire	https://www.mountainproject.com/route/107394225/lone-wolf	1	-1	Trad	5.6	1	80	43.80532	-71.84351
Chimney Sweeps	Yellowknife Buttress > *Rumney > New Hampshire	https://www.mountainproject.com/route/106855048/chimney-sweeps	0	-1	Trad	5.7	2	200	43.80532	-71.84351
Bridge to Nowhere	Yellowknife Buttress > *Rumney > New Hampshire	https://www.mountainproject.com/route/106825276/bridge-to-nowhere	3	-1	Sport	5.9	1		43.80532	-71.84351
Cow Patty	Yellowknife Buttress > *Rumney > New Hampshire	https://www.mountainproject.com/route/105930936/cow-patty	2.5	-1	Sport	5.10a	1	100	43.80532	-71.84351
Juno	Yellowknife Buttress > *Rumney > New Hampshire	https://www.mountainproject.com/route/111741297/juno	2.3	-1	Sport	5.10b	1	50	43.80532	-71.84351
Yellowknife	Yellowknife Buttress > *Rumney > New Hampshire	https://www.mountainproject.com/route/105929329/yellowknife	2.9	-1	Sport	5.10c	1	99	43.80532	-71.84351
Abbey Normal	Yellowknife Buttress > *Rumney > New Hampshire	https://www.mountainproject.com/route/105930945/abbey-normal	2.1	-1	Sport	5.10c	1		43.80532	-71.84351
Mosquito	Yellowknife Buttress > *Rumney > New Hampshire	https://www.mountainproject.com/route/105930949/mosquito	2.2	-1	Sport	5.10d	1		43.80532	-71.84351
Cannery Row	Yellowknife Buttress > *Rumney > New Hampshire	https://www.mountainproject.com/route/106244748/cannery-row	2.4	-1	Sport	5.10d	1	100	43.80532	-71.84351
Gifts From Attu	Yellowknife Buttress > *Rumney > New Hampshire	https://www.mountainproject.com/route/107344845/gifts-from-attu	2	-1	Sport	5.11a	1	60	43.80532	-71.84351
Lone Ranger	Yellowknife Buttress > *Rumney > New Hampshire	https://www.mountainproject.com/route/106473533/lone-ranger	1	-1	"Trad, Aid"	5.11 C0	2	200	43.80532	-71.84351
Nanook of the North	Yellowknife Buttress > *Rumney > New Hampshire	https://www.mountainproject.com/route/105966571/nanook-of-the-north	2.5	-1	Sport	5.11c	1		43.80532	-71.84351
Alaskan Arches	Yellowknife Buttress > *Rumney > New Hampshire	https://www.mountainproject.com/route/105912593/alaskan-arches	3.2	-1	Sport	5.11d	1		43.80532	-71.84351
Yukon Cornelius	Yellowknife Buttress > *Rumney > New Hampshire	https://www.mountainproject.com/route/106289028/yukon-cornelius	2.3	-1	Sport	5.11d	1	110	43.80532	-71.84351
Aurora Borealis	Yellowknife Buttress > *Rumney > New Hampshire	https://www.mountainproject.com/route/106680817/aurora-borealis	2	-1	Sport	5.11d	1	65	43.80532	-71.84351
Sixth Sense	Below the New Wave > *Rumney > New Hampshire	https://www.mountainproject.com/route/105921786/sixth-sense	1.3	-1	Sport	5.6	1	30	43.8021	-71.8367
Son of Sammy	Below the New Wave > *Rumney > New Hampshire	https://www.mountainproject.com/route/105921754/son-of-sammy	2.1	-1	Sport	5.8+	1	30	43.8021	-71.8367
Couch Potato	Below the New Wave > *Rumney > New Hampshire	https://www.mountainproject.com/route/105921772/couch-potato	2	-1	Sport	5.9	1	30	43.8021	-71.8367
Bullwinkle Goes Ballistic	Below the New Wave > *Rumney > New Hampshire	https://www.mountainproject.com/route/106009353/bullwinkle-goes-ballistic	1.9	-1	Sport	5.10a	1		43.8021	-71.8367
Debbie Does CPR	Below the New Wave > *Rumney > New Hampshire	https://www.mountainproject.com/route/105921711/debbie-does-cpr	2.2	-1	Sport	5.11a	1	30	43.8021	-71.8367
Bullwinkle Craters	Below the New Wave > *Rumney > New Hampshire	https://www.mountainproject.com/route/105921731/bullwinkle-craters	2.3	-1	Sport	5.11b	1	40	43.8021	-71.8367
Monster Crossing	Monsters from the Id > *Rumney > New Hampshire	https://www.mountainproject.com/route/105984278/monster-crossing	1	-1	Sport	5.10c	1		43.80226	-71.83997
Heaven	Monsters from the Id > *Rumney > New Hampshire	https://www.mountainproject.com/route/105925313/heaven	3	-1	Sport	5.11a	1		43.80226	-71.83997
Abominable Snowman	Monsters from the Id > *Rumney > New Hampshire	https://www.mountainproject.com/route/105966743/abominable-snowman	1.7	-1	Sport	5.11b	1		43.80226	-71.83997
Heavenly Monsters	Monsters from the Id > *Rumney > New Hampshire	https://www.mountainproject.com/route/105984289/heavenly-monsters	2.4	-1	Sport	5.11b	1		43.80226	-71.83997
Little Demon	Monsters from the Id > *Rumney > New Hampshire	https://www.mountainproject.com/route/105966728/little-demon	1.7	-1	Sport	5.11b/c	1		43.80226	-71.83997
Source of Madness	Monsters from the Id > *Rumney > New Hampshire	https://www.mountainproject.com/route/105966733/source-of-madness	1.1	-1	Sport	5.11d	1		43.80226	-71.83997
Pee Wee's Playhouse	Upper Darth Vader > *Rumney > New Hampshire	https://www.mountainproject.com/route/105926287/pee-wees-playhouse	1.8	-1	Sport	5.4	1		43.80417	-71.84094
Blustery Day	Upper Darth Vader > *Rumney > New Hampshire	https://www.mountainproject.com/route/105955587/blustery-day	1.9	-1	Sport	5.6	1	25	43.80417	-71.84094
Frosted Flakes	Upper Darth Vader > *Rumney > New Hampshire	https://www.mountainproject.com/route/105926144/frosted-flakes	2.5	-1	Sport	5.7	1		43.80417	-71.84094
Victim of Love	Upper Darth Vader > *Rumney > New Hampshire	https://www.mountainproject.com/route/105955591/victim-of-love	1.9	-1	Sport	5.8	1	25	43.80417	-71.84094
Danger	Upper Darth Vader > *Rumney > New Hampshire	https://www.mountainproject.com/route/105966691/danger	2	-1	Trad	5.10a R	1		43.80417	-71.84094
Squall	Upper Darth Vader > *Rumney > New Hampshire	https://www.mountainproject.com/route/105955582/squall	2.3	-1	Sport	5.10c/d	1	25	43.80417	-71.84094
Three Easy Pieces	Upper Darth Vader > *Rumney > New Hampshire	https://www.mountainproject.com/route/105926283/three-easy-pieces	2.7	-1	Sport	5.11a	1		43.80417	-71.84094
Team Cream Puff	The Hinterlands > *Rumney > New Hampshire	https://www.mountainproject.com/route/117287232/team-cream-puff	2.3	-1	Sport	5.6	1	80	43.80505	-71.84309
Sprite	The Hinterlands > *Rumney > New Hampshire	https://www.mountainproject.com/route/117568844/sprite	2.1	-1	Sport	5.6	1	60	43.80505	-71.84309
Free Range Chicken	The Hinterlands > *Rumney > New Hampshire	https://www.mountainproject.com/route/106003114/free-range-chicken	1.6	-1	Trad	5.7	1		43.80505	-71.84309
Hinterland Highway	The Hinterlands > *Rumney > New Hampshire	https://www.mountainproject.com/route/106003130/hinterland-highway	2.4	-1	Sport	5.7	1		43.80505	-71.84309
Cold Feet	The Hinterlands > *Rumney > New Hampshire	https://www.mountainproject.com/route/106005938/cold-feet	2.4	-1	Sport	5.7	1		43.80505	-71.84309
Hole in the Wall	The Hinterlands > *Rumney > New Hampshire	https://www.mountainproject.com/route/106003120/hole-in-the-wall	2.2	-1	Trad	5.8	1		43.80505	-71.84309
Chicken Head	The Hinterlands > *Rumney > New Hampshire	https://www.mountainproject.com/route/106064374/chicken-head	2.1	-1	Sport	5.8	1		43.80505	-71.84309
Black Ice Cooler	The Hinterlands > *Rumney > New Hampshire	https://www.mountainproject.com/route/117235518/black-ice-cooler	2.3	-1	Sport	5.8	1	75	43.80505	-71.84309
What's Nokken?	The Hinterlands > *Rumney > New Hampshire	https://www.mountainproject.com/route/117235553/whats-nokken	1.8	-1	Sport	5.8	1	55	43.80505	-71.84309
Electric Socks	The Hinterlands > *Rumney > New Hampshire	https://www.mountainproject.com/route/105931501/electric-socks	2.6	-1	Sport	5.8+	1		43.80505	-71.84309
Who Done It?	The Hinterlands > *Rumney > New Hampshire	https://www.mountainproject.com/route/105931511/who-done-it	0.8	-1	Trad	5.9	1		43.80505	-71.84309
Pussyfoot	The Hinterlands > *Rumney > New Hampshire	https://www.mountainproject.com/route/117569459/pussyfoot	2.2	-1	Sport	5.9	1	75	43.80505	-71.84309
Barbed Wire Corner	The Hinterlands > *Rumney > New Hampshire	https://www.mountainproject.com/route/106738424/barbed-wire-corner	1.8	-1	Trad	5.9 R	1		43.80505	-71.84309
Killers Crack	The Hinterlands > *Rumney > New Hampshire	https://www.mountainproject.com/route/106147648/killers-crack	1.3	-1	Trad	5.9+	1	50	43.80505	-71.84309
Black Slabbath	The Hinterlands > *Rumney > New Hampshire	https://www.mountainproject.com/route/106013503/black-slabbath	2.5	-1	Sport	5.9+	1		43.80505	-71.84309
Jolt	The Hinterlands > *Rumney > New Hampshire	https://www.mountainproject.com/route/105931493/jolt	3.5	-1	Sport	5.10a	1		43.80505	-71.84309
Dolt	The Hinterlands > *Rumney > New Hampshire	https://www.mountainproject.com/route/105931527/dolt	2.9	-1	Sport	5.10a	1		43.80505	-71.84309
Back Crack	The Hinterlands > *Rumney > New Hampshire	https://www.mountainproject.com/route/107614065/back-crack	1.8	-1	Trad	5.10a	1	60	43.80505	-71.84309
Chicken Parts	The Hinterlands > *Rumney > New Hampshire	https://www.mountainproject.com/route/106036854/chicken-parts	2.2	-1	Sport	5.10a/b	1		43.80505	-71.84309
The Little People	The Hinterlands > *Rumney > New Hampshire	https://www.mountainproject.com/route/106131105/the-little-people	1.9	-1	Sport	5.10b	1	70	43.80505	-71.84309
Last Kid Picked	The Hinterlands > *Rumney > New Hampshire	https://www.mountainproject.com/route/106680881/last-kid-picked	2	-1	Sport	5.10b	1	50	43.80505	-71.84309
Moxie	The Hinterlands > *Rumney > New Hampshire	https://www.mountainproject.com/route/107623406/moxie	1.7	-1	"Trad, Aid"	5.10 C0	1	50	43.80505	-71.84309
Know Moxie	The Hinterlands > *Rumney > New Hampshire	https://www.mountainproject.com/route/107633843/know-moxie	2.5	-1	Trad	5.1	1	40	43.80505	-71.84309
Hot Head	The Hinterlands > *Rumney > New Hampshire	https://www.mountainproject.com/route/106013514/hot-head	2	-1	Sport	5.10c	1		43.80505	-71.84309
Tang	The Hinterlands > *Rumney > New Hampshire	https://www.mountainproject.com/route/106013451/tang	2.1	-1	Sport	5.10d	1		43.80505	-71.84309
Rise Against	The Hinterlands > *Rumney > New Hampshire	https://www.mountainproject.com/route/112304225/rise-against	3.1	-1	Sport	5.11b	1	85	43.80505	-71.84309
Live a Muerte	The Hinterlands > *Rumney > New Hampshire	https://www.mountainproject.com/route/116605073/live-a-muerte	2.5	-1	Sport	5.11b	1	45	43.80505	-71.84309
Nicky's Crack	The Hinterlands > *Rumney > New Hampshire	https://www.mountainproject.com/route/105931536/nickys-crack	3.1	-1	Sport	5.11d	1		43.80505	-71.84309
Slack	Armed and Dangerous (Main Cliff Left) > *Rumney > New Hampshire	https://www.mountainproject.com/route/106018063/slack	1.8	-1	Trad	5.5	1		43.80202	-71.83678
Brendan's Bitches	Armed and Dangerous (Main Cliff Left) > *Rumney > New Hampshire	https://www.mountainproject.com/route/106054645/brendans-bitches	1	-1	Trad	5.6	1		43.80202	-71.83678
Rainbow	Armed and Dangerous (Main Cliff Left) > *Rumney > New Hampshire	https://www.mountainproject.com/route/106054653/rainbow	2.1	-1	Sport	5.6	1		43.80202	-71.83678
Barbershop Duet	Armed and Dangerous (Main Cliff Left) > *Rumney > New Hampshire	https://www.mountainproject.com/route/106791802/barbershop-duet	2	-1	Trad	5.6 PG13	1	60	43.80202	-71.83678
The Big Easy	Armed and Dangerous (Main Cliff Left) > *Rumney > New Hampshire	https://www.mountainproject.com/route/106052151/the-big-easy	2.6	-1	Sport	5.7	2		43.80202	-71.83678
Toxic Gumbo	Armed and Dangerous (Main Cliff Left) > *Rumney > New Hampshire	https://www.mountainproject.com/route/106148885/toxic-gumbo	2.5	-1	Sport	5.8	1	80	43.80202	-71.83678
The Anchovy Caper	Armed and Dangerous (Main Cliff Left) > *Rumney > New Hampshire	https://www.mountainproject.com/route/106148899/the-anchovy-caper	2	-1	Sport	5.8	1		43.80202	-71.83678
The Maltese Falcon	Armed and Dangerous (Main Cliff Left) > *Rumney > New Hampshire	https://www.mountainproject.com/route/107543321/the-maltese-falcon	2.4	-1	Sport	5.8	1	50	43.80202	-71.83678
Mentally Disturbed	Armed and Dangerous (Main Cliff Left) > *Rumney > New Hampshire	https://www.mountainproject.com/route/109491316/mentally-disturbed	2.1	-1	Sport	5.8	1		43.80202	-71.83678
Metamorphosis	Armed and Dangerous (Main Cliff Left) > *Rumney > New Hampshire	https://www.mountainproject.com/route/105959363/metamorphosis	3.3	-1	Sport	5.8+	1		43.80202	-71.83678
Bonnie and Clyde	Armed and Dangerous (Main Cliff Left) > *Rumney > New Hampshire	https://www.mountainproject.com/route/106884452/bonnie-and-clyde	1.9	-1	Sport	5.8+	1	50	43.80202	-71.83678
Slick	Armed and Dangerous (Main Cliff Left) > *Rumney > New Hampshire	https://www.mountainproject.com/route/111813417/slick	1.8	-1	Trad	5.9-	2		43.80202	-71.83678
Boats from Cuba	Armed and Dangerous (Main Cliff Left) > *Rumney > New Hampshire	https://www.mountainproject.com/route/108133264/boats-from-cuba	2.4	-1	Trad	5.9	1		43.80202	-71.83678
Men In White Suits	Armed and Dangerous (Main Cliff Left) > *Rumney > New Hampshire	https://www.mountainproject.com/route/105959381/men-in-white-suits	2.4	-1	Sport	5.9	1		43.80202	-71.83678
Green Mile	Armed and Dangerous (Main Cliff Left) > *Rumney > New Hampshire	https://www.mountainproject.com/route/106009586/green-mile	2.4	-1	Sport	5.9	1		43.80202	-71.83678
Panama Hat (aka Mister Meaner)	Armed and Dangerous (Main Cliff Left) > *Rumney > New Hampshire	https://www.mountainproject.com/route/106744657/panama-hat-aka-mister-meaner	2.4	-1	Sport	5.9+	1	60	43.80202	-71.83678
The White Buttress	Armed and Dangerous (Main Cliff Left) > *Rumney > New Hampshire	https://www.mountainproject.com/route/107392855/the-white-buttress	2	-1	Trad	5.9+	3		43.80202	-71.83678
Far From Feral	Armed and Dangerous (Main Cliff Left) > *Rumney > New Hampshire	https://www.mountainproject.com/route/107543333/far-from-feral	2	-1	Sport	5.10a	1	50	43.80202	-71.83678
"Arugula, Arugula"	Armed and Dangerous (Main Cliff Left) > *Rumney > New Hampshire	https://www.mountainproject.com/route/108005676/arugula-arugula	2.2	-1	Sport	5.10a	1	50	43.80202	-71.83678
Greener Pastures	Armed and Dangerous (Main Cliff Left) > *Rumney > New Hampshire	https://www.mountainproject.com/route/121172567/greener-pastures	2.6	-1	Sport	5.10a	3	50	43.80202	-71.83678
Scene of the Crime	Armed and Dangerous (Main Cliff Left) > *Rumney > New Hampshire	https://www.mountainproject.com/route/105947723/scene-of-the-crime	2.6	-1	Sport	5.10a	1		43.80202	-71.83678
Juicy Fingers	Armed and Dangerous (Main Cliff Left) > *Rumney > New Hampshire	https://www.mountainproject.com/route/106011991/juicy-fingers	2.4	-1	Trad	5.10a	1		43.80202	-71.83678
"Armed and Dangerous, and Off My Medication"	Armed and Dangerous (Main Cliff Left) > *Rumney > New Hampshire	https://www.mountainproject.com/route/105935097/armed-and-dangerous-and-off-my-medication	3.5	-1	Sport	5.10b	1		43.80202	-71.83678
Sesame Street	Armed and Dangerous (Main Cliff Left) > *Rumney > New Hampshire	https://www.mountainproject.com/route/105959390/sesame-street	3.1	-1	Sport	5.10b	1		43.80202	-71.83678
Fish Corner	Armed and Dangerous (Main Cliff Left) > *Rumney > New Hampshire	https://www.mountainproject.com/route/106543794/fish-corner	1.6	-1	"Sport, Boulder"	5.10b V1-	1	45	43.80202	-71.83678
Bourbon Street	Armed and Dangerous (Main Cliff Left) > *Rumney > New Hampshire	https://www.mountainproject.com/route/106054635/bourbon-street	2	-1	Sport	5.10c	1		43.80202	-71.83678
Clusterphobia	Armed and Dangerous (Main Cliff Left) > *Rumney > New Hampshire	https://www.mountainproject.com/route/105959353/clusterphobia	3	-1	Sport	5.10d	1		43.80202	-71.83678
Maria's Variation	Armed and Dangerous (Main Cliff Left) > *Rumney > New Hampshire	https://www.mountainproject.com/route/106168784/marias-variation	2.1	-1	Trad	5.11a	1		43.80202	-71.83678
Flying Squirrel	Armed and Dangerous (Main Cliff Left) > *Rumney > New Hampshire	https://www.mountainproject.com/route/106744677/flying-squirrel	3	-1	Sport	5.11a	1	50	43.80202	-71.83678
Climb and Punishment	Armed and Dangerous (Main Cliff Left) > *Rumney > New Hampshire	https://www.mountainproject.com/route/106891606/climb-and-punishment	2.1	-1	Sport	5.11b	1		43.80202	-71.83678
Half Nelson 5.7/ Full Nelson 5.11b	Armed and Dangerous (Main Cliff Left) > *Rumney > New Hampshire	https://www.mountainproject.com/route/106913131/half-nelson-57-full-nelson-511b	1.6	-1	Sport	5.11b	1	60	43.80202	-71.83678
Cereal Killer	Armed and Dangerous (Main Cliff Left) > *Rumney > New Hampshire	https://www.mountainproject.com/route/105935083/cereal-killer	2.9	-1	Sport	5.11c	1		43.80202	-71.83678
Cloud Atlas	Armed and Dangerous (Main Cliff Left) > *Rumney > New Hampshire	https://www.mountainproject.com/route/111696741/cloud-atlas	2.7	-1	Sport	5.11c	2	60	43.80202	-71.83678
Mitosis	Armed and Dangerous (Main Cliff Left) > *Rumney > New Hampshire	https://www.mountainproject.com/route/111687492/mitosis	2.9	-1	Sport	5.11d	1	40	43.80202	-71.83678
Give a Dog a Bone	Kennel Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/107342812/give-a-dog-a-bone	0.3	-1	Trad	5.4	1	40	43.80329	-71.83444
Giganthopicicus	Kennel Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/106144846/giganthopicicus	2.4	-1	Sport	5.6	1		43.80329	-71.83444
Bad Dog Crack	Kennel Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/106144836/bad-dog-crack	2	-1	Trad	5.7	1		43.80329	-71.83444
Puppy Love	Kennel Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/106137815/puppy-love	2	-1	Sport	5.9	1		43.80329	-71.83444
I'm Talking to The Dog	Kennel Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/106718896/im-talking-to-the-dog	1.7	-1	Sport	5.9+	1		43.80329	-71.83444
Ian's Arete	Kennel Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/106144850/ians-arete	1.9	-1	Sport	5.10a	1		43.80329	-71.83444
Ya Moe	Kennel Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/119258824/ya-moe	1.2	-1	Sport	5.10b	1	45	43.80329	-71.83444
Dog Star	Kennel Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/105965811/dog-star	2.4	-1	Sport	5.10b	1		43.80329	-71.83444
Sparking Poodles	Kennel Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/106137809/sparking-poodles	1.8	-1	Sport	5.10b	1		43.80329	-71.83444
Dog Biscuit	Kennel Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/105951717/dog-biscuit	2.7	-1	Sport	5.10c	1	60	43.80329	-71.83444
Zacker Cracker	Kennel Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/106409735/zacker-cracker	3.1	-1	Trad	5.10d	1	50	43.80329	-71.83444
Walking the Dog	Kennel Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/107917529/walking-the-dog	2.6	-1	Trad	5.10d	1	50	43.80329	-71.83444
The Big Angler	Kennel Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/106144856/the-big-angler	2.1	-1	Sport	5.11a	1		43.80329	-71.83444
F* *king the Dog	Kennel Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/105951695/f-king-the-dog	3	-1	Sport	5.11a	1	50	43.80329	-71.83444
Desolation Row	Pulse Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/107105278/desolation-row	0.7	-1	Trad	5.4	1	40	43.80313	-71.83493
Lazy Days	Pulse Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/105993590/lazy-days	1.8	-1	Sport	5.5	1	30	43.80313	-71.83493
Cliff Notes	Pulse Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/105993540/cliff-notes	1.9	-1	Trad	5.7	1	30	43.80313	-71.83493
Quickie Crack	Pulse Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/106055371/quickie-crack	0.7	-1	Trad	5.7	1	25	43.80313	-71.83493
Low Voltage	Pulse Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/106409719/low-voltage	1.2	-1	Trad	5.7	1	35	43.80313	-71.83493
Little Angler	Pulse Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/105993528/little-angler	2.2	-1	Sport	5.8	1		43.80313	-71.83493
Toy Story	Pulse Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/105939106/toy-story	2.2	-1	Trad	5.9	1		43.80313	-71.83493
Tool Story	Pulse Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/105993595/tool-story	1.7	-1	Trad	5.10b	1	40	43.80313	-71.83493
Tool Time	Pulse Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/105993599/tool-time	1.8	-1	Sport	5.10d	1		43.80313	-71.83493
Gulliver's Travels	Pulse Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/105956667/gullivers-travels	1.5	-1	Sport	5.11b	1	20	43.80313	-71.83493
Pulse	Pulse Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/105943709/pulse	3	-1	Sport	5.11d	1	35	43.80313	-71.83493
Yer Anus	Starship Enterprise > *Rumney > New Hampshire	https://www.mountainproject.com/route/105959760/yer-anus	2.3	-1	Sport	5.9	1		43.8021	-71.8367
Space	Starship Enterprise > *Rumney > New Hampshire	https://www.mountainproject.com/route/105959820/space	2.6	-1	Sport	5.9+	1		43.8021	-71.8367
Starship Enterprise	Starship Enterprise > *Rumney > New Hampshire	https://www.mountainproject.com/route/106784644/starship-enterprise	2	-1	Trad	5.9+ R	1	45	43.8021	-71.8367
Red Alert	Starship Enterprise > *Rumney > New Hampshire	https://www.mountainproject.com/route/105959750/red-alert	1.9	-1	Sport	5.10c	1		43.8021	-71.8367
The Romulan Route	Starship Enterprise > *Rumney > New Hampshire	https://www.mountainproject.com/route/105959733/the-romulan-route	2.2	-1	Sport	5.11a	1		43.8021	-71.8367
One Size Fits All	Starship Enterprise > *Rumney > New Hampshire	https://www.mountainproject.com/route/105959754/one-size-fits-all	2.2	-1	Sport	5.11b	1		43.8021	-71.8367
Pee Wee's Big Adventure	The Crow's Nest > *Rumney > New Hampshire	https://www.mountainproject.com/route/105966723/pee-wees-big-adventure	2.7	-1	Trad	5.4	1		43.80521	-71.84258
J-boat	The Crow's Nest > *Rumney > New Hampshire	https://www.mountainproject.com/route/106014679/j-boat	0.9	-1	Trad	5.6	1		43.80521	-71.84258
Scuttlebutt	The Crow's Nest > *Rumney > New Hampshire	https://www.mountainproject.com/route/106263810/scuttlebutt	2.2	-1	Sport	5.6	1	40	43.80521	-71.84258
The Little Mermaid	The Crow's Nest > *Rumney > New Hampshire	https://www.mountainproject.com/route/106454898/the-little-mermaid	2.4	-1	Sport	5.6	1	40	43.80521	-71.84258
Starboard Drift	The Crow's Nest > *Rumney > New Hampshire	https://www.mountainproject.com/route/106263819/starboard-drift	1.1	-1	Trad	5.7 PG13	1	45	43.80521	-71.84258
Woman Overboard	The Crow's Nest > *Rumney > New Hampshire	https://www.mountainproject.com/route/106263801/woman-overboard	1.5	-1	Sport	5.8	1	45	43.80521	-71.84258
Mussels	The Crow's Nest > *Rumney > New Hampshire	https://www.mountainproject.com/route/106704876/mussels	1.6	-1	Sport	5.8	1	40	43.80521	-71.84258
Land Ho!	The Crow's Nest > *Rumney > New Hampshire	https://www.mountainproject.com/route/106186138/land-ho	2.6	-1	Sport	5.8+	1		43.80521	-71.84258
Sea Breeze	The Crow's Nest > *Rumney > New Hampshire	https://www.mountainproject.com/route/106186163/sea-breeze	1.7	-1	Sport	5.9	1		43.80521	-71.84258
The Trad's Nest	The Crow's Nest > *Rumney > New Hampshire	https://www.mountainproject.com/route/106263806/the-trads-nest	1.9	-1	Sport	5.9	1	40	43.80521	-71.84258
Clambake	The Crow's Nest > *Rumney > New Hampshire	https://www.mountainproject.com/route/106442110/clambake	1.9	-1	Sport	5.9+	1	40	43.80521	-71.84258
Ill Gotten Booty	The Crow's Nest > *Rumney > New Hampshire	https://www.mountainproject.com/route/105965186/ill-gotten-booty	1.9	-1	Sport	5.9+	1		43.80521	-71.84258
Keel-Ho	The Crow's Nest > *Rumney > New Hampshire	https://www.mountainproject.com/route/106186148/keel-ho	2.5	-1	Sport	5.10a	1		43.80521	-71.84258
Mutiny	The Crow's Nest > *Rumney > New Hampshire	https://www.mountainproject.com/route/106442378/mutiny	2	-1	Sport	5.10b	1	30	43.80521	-71.84258
The Crow's Nest	The Crow's Nest > *Rumney > New Hampshire	https://www.mountainproject.com/route/106442350/the-crows-nest	2.5	-1	Sport	5.10c	1	40	43.80521	-71.84258
Calypso	The Crow's Nest > *Rumney > New Hampshire	https://www.mountainproject.com/route/106458215/calypso	2.2	-1	Sport	5.10c	1	40	43.80521	-71.84258
Corvus B.	The Crow's Nest > *Rumney > New Hampshire	https://www.mountainproject.com/route/106876334/corvus-b	2.6	-1	TR	5.10c	1	45	43.80521	-71.84258
S.O.S.	The Crow's Nest > *Rumney > New Hampshire	https://www.mountainproject.com/route/105965199/sos	2.5	-1	Sport	5.11a	1		43.80521	-71.84258
Walk the Plank	The Crow's Nest > *Rumney > New Hampshire	https://www.mountainproject.com/route/105965195/walk-the-plank	2.4	-1	Sport	5.11b	1		43.80521	-71.84258
The Dingy	The Crow's Nest > *Rumney > New Hampshire	https://www.mountainproject.com/route/106186124/the-dingy	2.2	-1	Sport	5.11b	1	20	43.80521	-71.84258
Seasick	The Crow's Nest > *Rumney > New Hampshire	https://www.mountainproject.com/route/105965171/seasick	2	-1	Sport	5.11c	1	30	43.80521	-71.84258
Saint Elmo's Fire	The Crow's Nest > *Rumney > New Hampshire	https://www.mountainproject.com/route/106181076/saint-elmos-fire	2.3	-1	Sport	5.11d	1		43.80521	-71.84258
Easy Street	Main Cliff Right > *Rumney > New Hampshire	https://www.mountainproject.com/route/106070815/easy-street	2	-1	Trad	5.3	1		43.8027	-71.83554
Run Out	Main Cliff Right > *Rumney > New Hampshire	https://www.mountainproject.com/route/106070827/run-out	1	-1	Trad	5.4	1		43.8027	-71.83554
Wendell's Route	Main Cliff Right > *Rumney > New Hampshire	https://www.mountainproject.com/route/106057531/wendells-route	1.3	-1	Trad	5.6	1	200	43.8027	-71.83554
Model Citizen	Main Cliff Right > *Rumney > New Hampshire	https://www.mountainproject.com/route/111862143/model-citizen	2.7	-1	Sport	5.6	2	115	43.8027	-71.83554
Crowd Pleaser	Main Cliff Right > *Rumney > New Hampshire	https://www.mountainproject.com/route/110508566/crowd-pleaser	2.7	-1	Sport	5.7	2		43.8027	-71.83554
Gentleman's Route	Main Cliff Right > *Rumney > New Hampshire	https://www.mountainproject.com/route/114528275/gentlemans-route	2.8	-1	Sport	5.7	3	180	43.8027	-71.83554
Magic Daze	Main Cliff Right > *Rumney > New Hampshire	https://www.mountainproject.com/route/117076813/magic-daze	2.3	-1	Sport	5.7	1	90	43.8027	-71.83554
White Toad	Main Cliff Right > *Rumney > New Hampshire	https://www.mountainproject.com/route/106018089/white-toad	2.7	-1	Trad	5.7	3	180	43.8027	-71.83554
Dead Toad	Main Cliff Right > *Rumney > New Hampshire	https://www.mountainproject.com/route/106018100/dead-toad	2.4	-1	Sport	5.8	1		43.8027	-71.83554
Cherry Pie	Main Cliff Right > *Rumney > New Hampshire	https://www.mountainproject.com/route/107376925/cherry-pie	2.5	-1	Trad	5.8	2	200	43.8027	-71.83554
Tipping Point	Main Cliff Right > *Rumney > New Hampshire	https://www.mountainproject.com/route/110494969/tipping-point	2.7	-1	Sport	5.8	2		43.8027	-71.83554
Crack Addict	Main Cliff Right > *Rumney > New Hampshire	https://www.mountainproject.com/route/110651594/crack-addict	2.6	-1	Sport	5.8	1	80	43.8027	-71.83554
Tour De Toad	Main Cliff Right > *Rumney > New Hampshire	https://www.mountainproject.com/route/110540900/tour-de-toad	2.8	-1	Sport	5.9	3	200	43.8027	-71.83554
Charity Case	Main Cliff Right > *Rumney > New Hampshire	https://www.mountainproject.com/route/106018125/charity-case	2.1	-1	Sport	5.9	1		43.8027	-71.83554
Charity Toad	Main Cliff Right > *Rumney > New Hampshire	https://www.mountainproject.com/route/106018140/charity-toad	2.7	-1	Sport	5.9	3	180	43.8027	-71.83554
Happy Hooker	Main Cliff Right > *Rumney > New Hampshire	https://www.mountainproject.com/route/106201831/happy-hooker	0.9	-1	Trad	5.10a PG13	1		43.8027	-71.83554
Stairway to Heaven	Main Cliff Right > *Rumney > New Hampshire	https://www.mountainproject.com/route/106694058/stairway-to-heaven	3.1	-1	Sport	5.10b	1	80	43.8027	-71.83554
Magic Helmet	Main Cliff Right > *Rumney > New Hampshire	https://www.mountainproject.com/route/107052784/magic-helmet	1.8	-1	Sport	5.10b	1	40	43.8027	-71.83554
Friendship Tower	Main Cliff Right > *Rumney > New Hampshire	https://www.mountainproject.com/route/106041026/friendship-tower	1.4	-1	Sport	5.10b	1		43.8027	-71.83554
Toady Dreams	Main Cliff Right > *Rumney > New Hampshire	https://www.mountainproject.com/route/106201844/toady-dreams	2.1	-1	Sport	5.10c	1		43.8027	-71.83554
Losing Eleven	Main Cliff Right > *Rumney > New Hampshire	https://www.mountainproject.com/route/117662975/losing-eleven	2.4	-1	Sport	5.11a/b	1	70	43.8027	-71.83554
Freebird	Main Cliff Right > *Rumney > New Hampshire	https://www.mountainproject.com/route/106057495/freebird	2.7	-1	Trad	5.11b	1	200	43.8027	-71.83554
High Roller	Main Cliff Right > *Rumney > New Hampshire	https://www.mountainproject.com/route/106283611/high-roller	3.4	-1	Sport	5.11c	2	160	43.8027	-71.83554
Stained Glass Ceiling	Main Cliff Right > *Rumney > New Hampshire	https://www.mountainproject.com/route/110544617/stained-glass-ceiling	2.4	-1	Sport	5.11c	2	60	43.8027	-71.83554
Boundary Route	Boundary Rock > *Rumney > New Hampshire	https://www.mountainproject.com/route/106102689/boundary-route	2.2	-1	Sport	5.8	1		43.8021	-71.8367
Outer Bounds	Boundary Rock > *Rumney > New Hampshire	https://www.mountainproject.com/route/106102681/outer-bounds	2.3	-1	Sport	5.8+	1		43.8021	-71.8367
Personal Boundaries	Boundary Rock > *Rumney > New Hampshire	https://www.mountainproject.com/route/110744830/personal-boundaries	1.6	-1	Sport	5.9+	1		43.8021	-71.8367
Imaginations of the Heart	Boundary Rock > *Rumney > New Hampshire	https://www.mountainproject.com/route/110525285/imaginations-of-the-heart	2	-1	Sport	5.10a	1	40	43.8021	-71.8367
No Boundaries (Link Up)	Boundary Rock > *Rumney > New Hampshire	https://www.mountainproject.com/route/123382640/no-boundaries-link-up	3	-1	Sport	5.10b	1	45	43.8021	-71.8367
Shine On	The Northwest Territories > *Rumney > New Hampshire	https://www.mountainproject.com/route/109601770/shine-on	2.4	-1	Sport	5.5	1	55	43.80478	-71.84537
The Beastie	The Northwest Territories > *Rumney > New Hampshire	https://www.mountainproject.com/route/109586856/the-beastie	2.2	-1	Sport	5.7	1	50	43.80478	-71.84537
Air Barrier	The Northwest Territories > *Rumney > New Hampshire	https://www.mountainproject.com/route/110479688/air-barrier	2.4	-1	Sport	5.7	1	50	43.80478	-71.84537
Times Like These	The Northwest Territories > *Rumney > New Hampshire	https://www.mountainproject.com/route/110497832/times-like-these	1.8	-1	Sport	5.7	1	40	43.80478	-71.84537
Like Old Times	The Northwest Territories > *Rumney > New Hampshire	https://www.mountainproject.com/route/108405945/like-old-times	2.2	-1	Sport	5.8	1		43.80478	-71.84537
Primitive Times	The Northwest Territories > *Rumney > New Hampshire	https://www.mountainproject.com/route/107846954/primitive-times	0	-1	Trad	5.8	1		43.80478	-71.84537
Approaching Armageddon	The Northwest Territories > *Rumney > New Hampshire	https://www.mountainproject.com/route/106887464/approaching-armageddon	2	-1	Trad	5.8+	2	90	43.80478	-71.84537
Paper Wafer	The Northwest Territories > *Rumney > New Hampshire	https://www.mountainproject.com/route/106147505/paper-wafer	2.3	-1	Trad	5.9	1	60	43.80478	-71.84537
B-B-Buttress	The Northwest Territories > *Rumney > New Hampshire	https://www.mountainproject.com/route/106147475/b-b-buttress	3	-1	Sport	5.9+	1		43.80478	-71.84537
California Chrome	The Northwest Territories > *Rumney > New Hampshire	https://www.mountainproject.com/route/108999586/california-chrome	2.5	-1	Sport	5.9+	1	100	43.80478	-71.84537
B-B-Bubbas link-up	The Northwest Territories > *Rumney > New Hampshire	https://www.mountainproject.com/route/108999668/b-b-bubbas-link-up	3	-1	Sport	5.10a	1	100	43.80478	-71.84537
Winter is Coming	The Northwest Territories > *Rumney > New Hampshire	https://www.mountainproject.com/route/116790121/winter-is-coming	2.6	-1	Sport	5.10c	1	35	43.80478	-71.84537
Beerless Leader	The Northwest Territories > *Rumney > New Hampshire	https://www.mountainproject.com/route/107846939/beerless-leader	1.8	-1	Trad	5.10c	1		43.80478	-71.84537
Scrubbing Bubbas	The Northwest Territories > *Rumney > New Hampshire	https://www.mountainproject.com/route/106775808/scrubbing-bubbas	1.4	-1	Sport	5.11a	1	90	43.80478	-71.84537
Gestaltwandler	The Northwest Territories > *Rumney > New Hampshire	https://www.mountainproject.com/route/120942734/gestaltwandler	2.1	-1	Sport	5.11+	1	35	43.80478	-71.84537
Hard Times	The Northwest Territories > *Rumney > New Hampshire	https://www.mountainproject.com/route/106694077/hard-times	2.2	-1	Sport	5.11d	1	60	43.80478	-71.84537
Crazy Pills	The Asylum > *Rumney > New Hampshire	https://www.mountainproject.com/route/118017010/crazy-pills	2.3	-1	Sport	5.7	1	65	43.80527	-71.84431
Nest Egg	The Asylum > *Rumney > New Hampshire	https://www.mountainproject.com/route/118018073/nest-egg	1	-1	Trad	5.7	1	30	43.80527	-71.84431
BBQ for Buddha	The Asylum > *Rumney > New Hampshire	https://www.mountainproject.com/route/106533164/bbq-for-buddha	2.3	-1	Sport	5.7+	1		43.80527	-71.84431
Cuckoo's Nest	The Asylum > *Rumney > New Hampshire	https://www.mountainproject.com/route/106289000/cuckoos-nest	1.4	-1	Sport	5.10d	1	25	43.80527	-71.84431
Pile-o-mania	The Asylum > *Rumney > New Hampshire	https://www.mountainproject.com/route/106289012/pile-o-mania	3.1	-1	Sport	5.10d	1	50	43.80527	-71.84431
Brain Surgery 101	The Asylum > *Rumney > New Hampshire	https://www.mountainproject.com/route/106680836/brain-surgery-101	2.8	-1	Sport	5.11b	1	50	43.80527	-71.84431
Virtual Insanity	The Asylum > *Rumney > New Hampshire	https://www.mountainproject.com/route/118087626/virtual-insanity	2	-1	Sport	5.11b	1	100	43.80527	-71.84431
The Asylum	The Asylum > *Rumney > New Hampshire	https://www.mountainproject.com/route/106533705/the-asylum	2.8	-1	Sport	5.11c	1	50	43.80527	-71.84431
"I Had a Good Name, But I Forgot (AKA for Lee, 'The route with the Epic Name')"	The Asylum > *Rumney > New Hampshire	https://www.mountainproject.com/route/107648801/i-had-a-good-name-but-i-forgot-aka-for-lee-the-route-with-the-epic-name	3.1	-1	Sport	5.11c	1	60	43.80527	-71.84431
Innocent Prairie Dog	Buffalo Pit > *Rumney > New Hampshire	https://www.mountainproject.com/route/114398942/innocent-prairie-dog	1.5	-1	Sport	5.1	1	40	43.80386	-71.84992
Mr. Buffoolo To You	Buffalo Pit > *Rumney > New Hampshire	https://www.mountainproject.com/route/113501788/mr-buffoolo-to-you	1.9	-1	Sport	5.4	1	45	43.80386	-71.84992
Buffalo Chips	Buffalo Pit > *Rumney > New Hampshire	https://www.mountainproject.com/route/107874611/buffalo-chips	0	-1	Trad	5.5	1	80	43.80386	-71.84992
Nicely Stacked	Buffalo Pit > *Rumney > New Hampshire	https://www.mountainproject.com/route/106289989/nicely-stacked	1.6	-1	Trad	5.7	2		43.80386	-71.84992
Rainy Day	Buffalo Pit > *Rumney > New Hampshire	https://www.mountainproject.com/route/106744844/rainy-day	1.8	-1	Trad	5.7	1	60	43.80386	-71.84992
Hobo Nickel	Buffalo Pit > *Rumney > New Hampshire	https://www.mountainproject.com/route/114445380/hobo-nickel	2.1	-1	Trad	5.7	1	85	43.80386	-71.84992
Something Fishy	Buffalo Pit > *Rumney > New Hampshire	https://www.mountainproject.com/route/106289977/something-fishy	1.9	-1	Trad	5.7+	2		43.80386	-71.84992
Lonesome Buffalo	Buffalo Pit > *Rumney > New Hampshire	https://www.mountainproject.com/route/113501882/lonesome-buffalo	2.9	-1	Sport	5.8	1	100	43.80386	-71.84992
Stone Worms	Buffalo Pit > *Rumney > New Hampshire	https://www.mountainproject.com/route/114447316/stone-worms	2.5	-1	Sport	5.9-	1	90	43.80386	-71.84992
Sodbuster	Buffalo Pit > *Rumney > New Hampshire	https://www.mountainproject.com/route/113501901/sodbuster	2.2	-1	Sport	5.9	1	80	43.80386	-71.84992
Scratchy	Buffalo Pit > *Rumney > New Hampshire	https://www.mountainproject.com/route/114395090/scratchy	1.9	-1	Sport	5.9	1	35	43.80386	-71.84992
Fresh Fish	Buffalo Pit > *Rumney > New Hampshire	https://www.mountainproject.com/route/117287185/fresh-fish	2.5	-1	Sport	5.9+	1	80	43.80386	-71.84992
Barefoot	Buffalo Pit > *Rumney > New Hampshire	https://www.mountainproject.com/route/114303295/barefoot	2.2	-1	Trad	5.10a/b	1	45	43.80386	-71.84992
Out Of Order	Buffalo Pit > *Rumney > New Hampshire	https://www.mountainproject.com/route/113501083/out-of-order	2.6	-1	Sport	5.10c	1		43.80386	-71.84992
Sunnyside Up	Buffalo Pit > *Rumney > New Hampshire	https://www.mountainproject.com/route/113501814/sunnyside-up	2.4	-1	Sport	5.10c	1	45	43.80386	-71.84992
Itchy	Buffalo Pit > *Rumney > New Hampshire	https://www.mountainproject.com/route/114394983/itchy	2.4	-1	Sport	5.10c	1	35	43.80386	-71.84992
Buffalo Crack	Buffalo Pit > *Rumney > New Hampshire	https://www.mountainproject.com/route/106744821/buffalo-crack	2.5	-1	Trad	5.10c	2		43.80386	-71.84992
The Perfect Egg Drop	Buffalo Pit > *Rumney > New Hampshire	https://www.mountainproject.com/route/113501849/the-perfect-egg-drop	2	-1	TR	5.10d	1	45	43.80386	-71.84992
Tatanka	Buffalo Pit > *Rumney > New Hampshire	https://www.mountainproject.com/route/113501929/tatanka	2.6	-1	Sport	5.11b	1	35	43.80386	-71.84992
Vulture Breath	Buffalo Pit > *Rumney > New Hampshire	https://www.mountainproject.com/route/113505851/vulture-breath	2.3	-1	Sport	5.11b	1	50	43.80386	-71.84992
Another Roadside Distraction	Buffalo Pit > *Rumney > New Hampshire	https://www.mountainproject.com/route/113551645/another-roadside-distraction	3.2	-1	Sport	5.11b	1	40	43.80386	-71.84992
Side Piece	G-spot- Lower Wall > The G-Spot > *Rumney > New Hampshire	https://www.mountainproject.com/route/122601336/side-piece	2	-1	Sport	5.5	1	45	43.80262	-71.83398
G-Wiz	G-spot- Lower Wall > The G-Spot > *Rumney > New Hampshire	https://www.mountainproject.com/route/119396398/g-wiz	1.4	-1	Sport	5.6	1	35	43.80262	-71.83398
Sex Ed	G-spot- Lower Wall > The G-Spot > *Rumney > New Hampshire	https://www.mountainproject.com/route/119396436/sex-ed	1.6	-1	Sport	5.7	1	40	43.80262	-71.83398
The Glouberman Method	G-spot- Lower Wall > The G-Spot > *Rumney > New Hampshire	https://www.mountainproject.com/route/122601316/the-glouberman-method	2	-1	Sport	5.8	1	35	43.80262	-71.83398
Drip of Fools	G-spot- Lower Wall > The G-Spot > *Rumney > New Hampshire	https://www.mountainproject.com/route/106441298/drip-of-fools	1.8	-1	Sport	5.9	1	30	43.80262	-71.83398
Bumpin the Gate	G-spot- Upper Wall > The G-Spot > *Rumney > New Hampshire	https://www.mountainproject.com/route/106441340/bumpin-the-gate	2	-1	Sport	5.7	1		43.80262	-71.83398
She Goes Both Ways	G-spot- Upper Wall > The G-Spot > *Rumney > New Hampshire	https://www.mountainproject.com/route/106441360/she-goes-both-ways	2.1	-1	Sport	5.8	1		43.80262	-71.83398
Layback and Relax	G-spot- Upper Wall > The G-Spot > *Rumney > New Hampshire	https://www.mountainproject.com/route/106441346/layback-and-relax	2.4	-1	Sport	5.10b	1		43.80262	-71.83398
Lichen Lickin	G-spot- Upper Wall > The G-Spot > *Rumney > New Hampshire	https://www.mountainproject.com/route/106441367/lichen-lickin	1.7	-1	Sport	5.10d	1		43.80262	-71.83398
Drillin' in My Dreams	G-spot- Upper Wall > The G-Spot > *Rumney > New Hampshire	https://www.mountainproject.com/route/106441351/drillin-in-my-dreams	1.9	-1	Sport	5.11a	1		43.80262	-71.83398
Kagels and Locks	G-spot- Kagels and Locks > The G-Spot > *Rumney > New Hampshire	https://www.mountainproject.com/route/106441334/kagels-and-locks	1.5	-1	Sport	5.7	1		43.80262	-71.83398
Where the Wild Things Are	Summit Cliff (The Highlands) > *Rumney > New Hampshire	https://www.mountainproject.com/route/106875020/where-the-wild-things-are	2.5	-1	Sport	5.7	1		43.80549	-71.84378
Corax crack	Summit Cliff (The Highlands) > *Rumney > New Hampshire	https://www.mountainproject.com/route/112083439/corax-crack	2.2	-1	Trad	5.7	1	50	43.80549	-71.84378
Giant's Chimney	Summit Cliff (The Highlands) > *Rumney > New Hampshire	https://www.mountainproject.com/route/110785077/giants-chimney	2.7	-1	Trad	5.9 R	1	80	43.80549	-71.84378
The Yid Kid	Summit Cliff (The Highlands) > *Rumney > New Hampshire	https://www.mountainproject.com/route/106699524/the-yid-kid	2.1	-1	Sport	5.10a	1	80	43.80549	-71.84378
Aiming for the Pleiades	Summit Cliff (The Highlands) > *Rumney > New Hampshire	https://www.mountainproject.com/route/113708907/aiming-for-the-pleiades	2	-1	Sport	5.10-	1	80	43.80549	-71.84378
Path of the Righteous	Summit Cliff (The Highlands) > *Rumney > New Hampshire	https://www.mountainproject.com/route/106875000/path-of-the-righteous	3.1	-1	Sport	5.10b	1		43.80549	-71.84378
The Boy Who Cried Wolf	Summit Cliff (The Highlands) > *Rumney > New Hampshire	https://www.mountainproject.com/route/106699506/the-boy-who-cried-wolf	1.3	-1	Sport	5.10c	1	80	43.80549	-71.84378
Three Bump Dumper	Summit Cliff (The Highlands) > *Rumney > New Hampshire	https://www.mountainproject.com/route/106874987/three-bump-dumper	2.5	-1	Sport	5.11a	1	60	43.80549	-71.84378
Northern Lights	Summit Cliff (The Highlands) > *Rumney > New Hampshire	https://www.mountainproject.com/route/107138813/northern-lights	2	-1	Sport	5.11a	1		43.80549	-71.84378
Visions of Jerusalem	Summit Cliff (The Highlands) > *Rumney > New Hampshire	https://www.mountainproject.com/route/107697921/visions-of-jerusalem	2.4	-1	Sport	5.11a	1	60	43.80549	-71.84378
Rumpus Time	Summit Cliff (The Highlands) > *Rumney > New Hampshire	https://www.mountainproject.com/route/112566431/rumpus-time	3.1	-1	Sport	5.11a	1	55	43.80549	-71.84378
Northwest Passage	Summit Cliff (The Highlands) > *Rumney > New Hampshire	https://www.mountainproject.com/route/107138787/northwest-passage	2.7	-1	Sport	5.11b	2		43.80549	-71.84378
Passing on the Right	Summit Cliff (The Highlands) > *Rumney > New Hampshire	https://www.mountainproject.com/route/107263672/passing-on-the-right	3	-1	TR	5.11b	2		43.80549	-71.84378
The Gospel According to Mark	Summit Cliff (The Highlands) > *Rumney > New Hampshire	https://www.mountainproject.com/route/107391121/the-gospel-according-to-mark	3	-1	Sport	5.11c	1	75	43.80549	-71.84378
Dr. Dingle	Summit Cliff (The Highlands) > *Rumney > New Hampshire	https://www.mountainproject.com/route/109367925/dr-dingle	2	-1	Sport	5.11d	1	45	43.80549	-71.84378
Mr Mailman	The Bakery > *Rumney > New Hampshire	https://www.mountainproject.com/route/116788960/mr-mailman	2	-1	Trad	5.8	1	25	43.8027	-71.8293
Golden Glove	The Bakery > *Rumney > New Hampshire	https://www.mountainproject.com/route/106604491/golden-glove	1	-1	Trad	5.10a	1	40	43.8027	-71.8293
Rookie Sensation	The Bakery > *Rumney > New Hampshire	https://www.mountainproject.com/route/106604483/rookie-sensation	2.2	-1	Sport	5.10d	1	40	43.8027	-71.8293
Sport Moves	The Bakery > *Rumney > New Hampshire	https://www.mountainproject.com/route/106604472/sport-moves	2	-1	Sport	5.11a	1	40	43.8027	-71.8293
Bad Sneakers	Wonderland > *Rumney > New Hampshire	https://www.mountainproject.com/route/106728788/bad-sneakers	0	-1	"Trad, Alpine"	5.3 R	1	40	43.8021	-71.8367
Fixing a hole	Wonderland > *Rumney > New Hampshire	https://www.mountainproject.com/route/106720297/fixing-a-hole	0	-1	"Trad, Alpine"	5.5	2	150	43.8021	-71.8367
Senior Citizen Route	Wonderland > *Rumney > New Hampshire	https://www.mountainproject.com/route/106732997/senior-citizen-route	0	-1	"Trad, Alpine"	5.5 R	2	100	43.8021	-71.8367
Beat the Heat	Wonderland > *Rumney > New Hampshire	https://www.mountainproject.com/route/106858320/beat-the-heat	1.5	-1	"Trad, Alpine"	5.5	1	100	43.8021	-71.8367
White Tuxedo	Wonderland > *Rumney > New Hampshire	https://www.mountainproject.com/route/106858350/white-tuxedo	1	-1	"Trad, Alpine"	5.5	1	40	43.8021	-71.8367
Wendall's Dike	Wonderland > *Rumney > New Hampshire	https://www.mountainproject.com/route/107233478/wendalls-dike	0.5	-1	"Trad, Alpine"	5.5 R	1	120	43.8021	-71.8367
White Rabbit	Wonderland > *Rumney > New Hampshire	https://www.mountainproject.com/route/107233508/white-rabbit	1	-1	"Trad, Alpine"	5.5 PG13	3	200	43.8021	-71.8367
Chesire Cat	Wonderland > *Rumney > New Hampshire	https://www.mountainproject.com/route/107280089/chesire-cat	2.5	-1	"Sport, Alpine"	5.6 R	1	40	43.8021	-71.8367
Rocket Science	Wonderland > *Rumney > New Hampshire	https://www.mountainproject.com/route/106720288/rocket-science	2.3	-1	"Sport, Alpine"	5.8+	1	70	43.8021	-71.8367
Magnum Opus	Wonderland > *Rumney > New Hampshire	https://www.mountainproject.com/route/107362969/magnum-opus	0	-1	"Trad, Alpine"	5.10a	1	50	43.8021	-71.8367
Wrong Turn	Wonderland > *Rumney > New Hampshire	https://www.mountainproject.com/route/106723270/wrong-turn	1.5	-1	"Trad, TR, Alpine"	5.10c PG13	1	25	43.8021	-71.8367
So Alone	Wonderland > *Rumney > New Hampshire	https://www.mountainproject.com/route/106858279/so-alone	3	-1	"Sport, Alpine"	5.11b/c	1	40	43.8021	-71.8367
Triple Delights	Triple Corners Left > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/106261485/triple-delights	2	-1	Sport	5.4	1		43.80406	-71.84251
Way off route	Triple Corners Left > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/107333100/way-off-route	0	-1	Trad	5.4 X	2	200	43.80406	-71.84251
Birch Corner	Triple Corners Left > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/106424373/birch-corner	2	-1	Trad	5.7+	1	50	43.80406	-71.84251
Loose and Baggy	Triple Corners Left > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/106261478/loose-and-baggy	1.9	-1	Sport	5.8+	1	40	43.80406	-71.84251
Ladybug Death Orgy	Triple Corners Left > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/106480216/ladybug-death-orgy	1.8	-1	Trad	5.8+ PG13	1	50	43.80406	-71.84251
Triple Fisting	Triple Corners Left > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/106435859/triple-fisting	1.9	-1	Trad	5.9	1	45	43.80406	-71.84251
Birch Fist	Triple Corners Left > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/106463520/birch-fist	1.5	-1	Trad	5.9	1	50	43.80406	-71.84251
Where am I ?	Triple Corners Left > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/106435834/where-am-i	1.3	-1	Sport	5.10a	1	50	43.80406	-71.84251
That's a Moray	Triple Corners Left > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/111151515/thats-a-moray	1	-1	Trad	5.10-	1	50	43.80406	-71.84251
Amore Eel	Triple Corners Left > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/106318889/amore-eel	2.4	-1	Sport	5.10b	1	50	43.80406	-71.84251
Man With a Hueco in His Tights	Triple Corners Left > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/105946055/man-with-a-hueco-in-his-tights	2.8	-1	Sport	5.11a	1	45	43.80406	-71.84251
Hassig's Libido	Triple Corners Left > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/106507847/hassigs-libido	1.7	-1	Trad	5.11c	1	50	43.80406	-71.84251
Lichen Flakes	Triple Corners Center > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/106355855/lichen-flakes	1.5	-1	Trad	5.3	1		43.80401	-71.84229
Big Worm	Triple Corners Center > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/106494178/big-worm	0.5	-1	Trad	5.7	1		43.80401	-71.84229
Lower Buttress Direct	Triple Corners Center > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/106721130/lower-buttress-direct	0.7	-1	Sport	5.8	1		43.80401	-71.84229
Logjam	Triple Corners Center > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/107215507/logjam	2	-1	Trad	5.8	1		43.80401	-71.84229
Stress Management	Triple Corners Center > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/106494878/stress-management	2.5	-1	Trad	5.9	1		43.80401	-71.84229
Reasons to be Cheerful	Triple Corners Center > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/106721145/reasons-to-be-cheerful	3.3	-1	Trad	5.9	1		43.80401	-71.84229
Trundle Love	Triple Corners Center > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/106721971/trundle-love	2.4	-1	Sport	5.9	1	30	43.80401	-71.84229
Central Corner	Triple Corners Center > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/107215526/central-corner	3	-1	Trad	5.9+	1		43.80401	-71.84229
Jammit Damnit	Triple Corners Center > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/106721107/jammit-damnit	2	-1	"Trad, Sport"	5.10b	1		43.80401	-71.84229
Skunks in the Gym	Triple Corners Center > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/106190876/skunks-in-the-gym	3.2	-1	Sport	5.10c	1		43.80401	-71.84229
The Full Effect	Triple Corners Center > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/106494144/the-full-effect	2.9	-1	Sport	5.10c	1		43.80401	-71.84229
Sergeant Schultz	Triple Corners Center > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/106490343/sergeant-schultz	1.5	-1	Sport	5.10d	1		43.80401	-71.84229
Twit	Triple Corners Center > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/107215545/twit	2.5	-1	Trad	5.10d	1		43.80401	-71.84229
Reasons to be Fearful	Triple Corners Center > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/107215563/reasons-to-be-fearful	3	-1	TR	5.11a	1		43.80401	-71.84229
Lichen Dike	Triple Corners Right > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/106030526/lichen-dike	0	-1	Trad	5.6	2	100	43.80403	-71.84178
Rack for Sale	Triple Corners Right > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/106029128/rack-for-sale	2.6	-1	Sport	5.7	1		43.80403	-71.84178
Still My Way	Triple Corners Right > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/110994870/still-my-way	2.2	-1	Sport	5.7	1	40	43.80403	-71.84178
Sun Bowl	Triple Corners Right > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/105956674/sun-bowl	1.9	-1	Sport	5.8	1	25	43.80403	-71.84178
Left El Diego	Triple Corners Right > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/105961439/left-el-diego	2.4	-1	Sport	5.9	1		43.80403	-71.84178
Trigger Happy	Triple Corners Right > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/106030531/trigger-happy	2.6	-1	Sport	5.9	1		43.80403	-71.84178
Spiders in the faith	Triple Corners Right > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/107233525/spiders-in-the-faith	2	-1	Trad	5.9 R	1	70	43.80403	-71.84178
Jigsaw Puzzle	Triple Corners Right > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/107728069/jigsaw-puzzle	1	-1	Sport	5.9+ PG13	1	35	43.80403	-71.84178
Murk Trench	Triple Corners Right > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/105956679/murk-trench	1.9	-1	Sport	5.10a	1	25	43.80403	-71.84178
Middle Man	Triple Corners Right > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/111772717/middle-man	2	-1	Sport	5.10b	1	35	43.80403	-71.84178
Chris Hassig's Memorial Route	Triple Corners Right > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/107233564/chris-hassigs-memorial-route	1.5	-1	Trad	5.10 R	1	70	43.80403	-71.84178
Technical Second	Triple Corners Right > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/106012950/technical-second	2.5	-1	Sport	5.10b/c	1		43.80403	-71.84178
Twelve Pack	Triple Corners Right > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/106030491/twelve-pack	2.2	-1	Sport	5.10d	1		43.80403	-71.84178
Dirty Dozen	Triple Corners Right > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/106030503/dirty-dozen	2.8	-1	Sport	5.10d	1		43.80403	-71.84178
Perfectly Blunt	Triple Corners Right > Triple Corners > *Rumney > New Hampshire	https://www.mountainproject.com/route/106200078/perfectly-blunt	2.3	-1	Sport	5.10d	1		43.80403	-71.84178
Rumney Rocks Climb	Utopia Ledges (True Summit Ledges) > *Rumney > New Hampshire	https://www.mountainproject.com/route/107393273/rumney-rocks-climb	0	-1	"Trad, Alpine"	5.4	2	200	43.8021	-71.8367
Beeker	Utopia Ledges (True Summit Ledges) > *Rumney > New Hampshire	https://www.mountainproject.com/route/107816878/beeker	1	-1	"Trad, Alpine"	5.4 R	1	70	43.8021	-71.8367
Jack O'Lantern	Utopia Ledges (True Summit Ledges) > *Rumney > New Hampshire	https://www.mountainproject.com/route/107855997/jack-olantern	3	-1	"Trad, Alpine"	5.4 R	1	100	43.8021	-71.8367
Freedonia	Utopia Ledges (True Summit Ledges) > *Rumney > New Hampshire	https://www.mountainproject.com/route/106733370/freedonia	2	-1	"Trad, Alpine"	5.5 PG13	3	200	43.8021	-71.8367
Hannah Flower	Utopia Ledges (True Summit Ledges) > *Rumney > New Hampshire	https://www.mountainproject.com/route/106733461/hannah-flower	1	-1	"Trad, Alpine"	5.5 R	2	200	43.8021	-71.8367
Bumble Bee	Utopia Ledges (True Summit Ledges) > *Rumney > New Hampshire	https://www.mountainproject.com/route/106743613/bumble-bee	0	-1	"Trad, Alpine"	5.5 PG13	2	150	43.8021	-71.8367
Makamah Road	Utopia Ledges (True Summit Ledges) > *Rumney > New Hampshire	https://www.mountainproject.com/route/106926092/makamah-road	0	-1	"Trad, Alpine"	5.5 R	2	200	43.8021	-71.8367
Jesus Nut	Utopia Ledges (True Summit Ledges) > *Rumney > New Hampshire	https://www.mountainproject.com/route/107394582/jesus-nut	1	-1	"Trad, Alpine"	5.5 R	1	200	43.8021	-71.8367
Maze	Utopia Ledges (True Summit Ledges) > *Rumney > New Hampshire	https://www.mountainproject.com/route/107518248/maze	0	-1	"Trad, Alpine"	5.5 R	1	40	43.8021	-71.8367
The Stones	Utopia Ledges (True Summit Ledges) > *Rumney > New Hampshire	https://www.mountainproject.com/route/107851638/the-stones	1	-1	"Trad, Alpine"	5.5	2	300	43.8021	-71.8367
Dystonia	Utopia Ledges (True Summit Ledges) > *Rumney > New Hampshire	https://www.mountainproject.com/route/107332110/dystonia	1	-1	"Trad, Alpine"	5.6 R	4	200	43.8021	-71.8367
Lost in Utopia	Utopia Ledges (True Summit Ledges) > *Rumney > New Hampshire	https://www.mountainproject.com/route/107742163/lost-in-utopia	1	-1	"Trad, Alpine"	5.6 R	2	100	43.8021	-71.8367
Ora the Explorer	Utopia Ledges (True Summit Ledges) > *Rumney > New Hampshire	https://www.mountainproject.com/route/107847740/ora-the-explorer	2	-1	"Trad, Alpine"	5.6 R	1	50	43.8021	-71.8367
Smashing Pumpkins	Utopia Ledges (True Summit Ledges) > *Rumney > New Hampshire	https://www.mountainproject.com/route/107858440/smashing-pumpkins	3	-1	"Trad, Alpine"	5.6 R	1	25	43.8021	-71.8367
Jack Knife	Utopia Ledges (True Summit Ledges) > *Rumney > New Hampshire	https://www.mountainproject.com/route/107887240/jack-knife	2	-1	"Trad, Alpine"	5.6 R	1	30	43.8021	-71.8367
Skywalker	Utopia Ledges (True Summit Ledges) > *Rumney > New Hampshire	https://www.mountainproject.com/route/107737403/skywalker	0	-1	"Trad, Alpine"	5.7 PG13	2	200	43.8021	-71.8367
Bag End	Gem Hunter > *Rumney > New Hampshire	https://www.mountainproject.com/route/106807582/bag-end	1.3	-1	Sport	5.7	1		43.8415	-71.8233
Quartz Course	Gem Hunter > *Rumney > New Hampshire	https://www.mountainproject.com/route/106811227/quartz-course	1.8	-1	Sport	5.7	1	30	43.8415	-71.8233
There and Back Again	Gem Hunter > *Rumney > New Hampshire	https://www.mountainproject.com/route/108206501/there-and-back-again	1.3	-1	Trad	5.7	1	35	43.8415	-71.8233
Crutch Factory	Gem Hunter > *Rumney > New Hampshire	https://www.mountainproject.com/route/106807598/crutch-factory	1.9	-1	Sport	5.8	1		43.8415	-71.8233
Spanning the Gap	Gem Hunter > *Rumney > New Hampshire	https://www.mountainproject.com/route/106807604/spanning-the-gap	2.3	-1	Sport	5.9	1		43.8415	-71.8233
Tourmaline Dreams	Gem Hunter > *Rumney > New Hampshire	https://www.mountainproject.com/route/106807642/tourmaline-dreams	1.6	-1	Sport	5.9	1		43.8415	-71.8233
Gem Hunter	Gem Hunter > *Rumney > New Hampshire	https://www.mountainproject.com/route/106811216/gem-hunter	1.3	-1	Sport	5.9+	1	45	43.8415	-71.8233
Helm's Deep	Gem Hunter > *Rumney > New Hampshire	https://www.mountainproject.com/route/106807592/helms-deep	1.4	-1	Sport	5.10a	1		43.8415	-71.8233
The Lidless Eye	Gem Hunter > *Rumney > New Hampshire	https://www.mountainproject.com/route/106807617/the-lidless-eye	1.8	-1	Sport	5.10a	1		43.8415	-71.8233
Rock Hound	Gem Hunter > *Rumney > New Hampshire	https://www.mountainproject.com/route/106807633/rock-hound	2	-1	Sport	5.10b	1		43.8415	-71.8233
Barefoot Boys With Shoes On	Gem Hunter > *Rumney > New Hampshire	https://www.mountainproject.com/route/108206533/barefoot-boys-with-shoes-on	2.5	-1	Sport	5.10d	1	35	43.8415	-71.8233
King of Crutches	Gem Hunter > *Rumney > New Hampshire	https://www.mountainproject.com/route/108206513/king-of-crutches	2.3	-1	Sport	5.11b	1	40	43.8415	-71.8233
Hour Glass Crack	The Black Jack Boulder > Black Jack Boulder Area > Black Jack Boulders > *Rumney Bouldering > *Rumney > New Hampshire	https://www.mountainproject.com/route/106121227/hour-glass-crack	2	-1	Trad	5.8	1		43.80288	-71.84167
Suicide Kings	The Black Jack Boulder > Black Jack Boulder Area > Black Jack Boulders > *Rumney Bouldering > *Rumney > New Hampshire	https://www.mountainproject.com/route/106545380/suicide-kings	3	-1	"Trad, TR"	5.10a	1	30	43.80288	-71.84167
The Space Between	The Black Jack Boulder > Black Jack Boulder Area > Black Jack Boulders > *Rumney Bouldering > *Rumney > New Hampshire	https://www.mountainproject.com/route/111241922/the-space-between	2	-1	TR	5.10+	1	30	43.80288	-71.84167
Black Jack Crack	The Black Jack Boulder > Black Jack Boulder Area > Black Jack Boulders > *Rumney Bouldering > *Rumney > New Hampshire	https://www.mountainproject.com/route/105899775/black-jack-crack	3.7	-1	"Trad, Boulder"	5.10d V2	1	30	43.80288	-71.84167
One Eyed Jack	The Black Jack Boulder > Black Jack Boulder Area > Black Jack Boulders > *Rumney Bouldering > *Rumney > New Hampshire	https://www.mountainproject.com/route/106541496/one-eyed-jack	2	-1	"Trad, TR, Boulder"	5.11c V3 R	1	30	43.80288	-71.84167
Three of Clubs	The Black Jack Boulder > Black Jack Boulder Area > Black Jack Boulders > *Rumney Bouldering > *Rumney > New Hampshire	https://www.mountainproject.com/route/108169985/three-of-clubs	0.5	-1	TR	5.11d	1	35	43.80288	-71.84167
Schist a side	Left of Venus Wall (The Bradley White Wall) > *Rumney > New Hampshire	https://www.mountainproject.com/route/106943248/schist-a-side	0	-1	Trad	5.4 R	1	40	43.8021	-71.8367
Singed	Left of Venus Wall (The Bradley White Wall) > *Rumney > New Hampshire	https://www.mountainproject.com/route/106953039/singed	0	-1	Trad	5.4 R	1	90	43.8021	-71.8367
Burned	Left of Venus Wall (The Bradley White Wall) > *Rumney > New Hampshire	https://www.mountainproject.com/route/107196068/burned	1	-1	Trad	5.4 R	1	50	43.8021	-71.8367
Kindling	Left of Venus Wall (The Bradley White Wall) > *Rumney > New Hampshire	https://www.mountainproject.com/route/107210797/kindling	2	-1	Trad	5.4 X	1	70	43.8021	-71.8367
Three Way Tie	Left of Venus Wall (The Bradley White Wall) > *Rumney > New Hampshire	https://www.mountainproject.com/route/107837841/three-way-tie	1	-1	Trad	5.4	1	50	43.8021	-71.8367
Morning Star	Left of Venus Wall (The Bradley White Wall) > *Rumney > New Hampshire	https://www.mountainproject.com/route/107887347/morning-star	1	-1	Trad	5.4 R	1	30	43.8021	-71.8367
Scorched	Left of Venus Wall (The Bradley White Wall) > *Rumney > New Hampshire	https://www.mountainproject.com/route/106948646/scorched	1	-1	Trad	5.5 R	3	200	43.8021	-71.8367
Edge	Left of Venus Wall (The Bradley White Wall) > *Rumney > New Hampshire	https://www.mountainproject.com/route/106960365/edge	0	-1	Trad	5.5 R	1	40	43.8021	-71.8367
Fire Proof	Left of Venus Wall (The Bradley White Wall) > *Rumney > New Hampshire	https://www.mountainproject.com/route/107196050/fire-proof	2	-1	Trad	5.5 R	1	30	43.8021	-71.8367
Flame	Left of Venus Wall (The Bradley White Wall) > *Rumney > New Hampshire	https://www.mountainproject.com/route/107210805/flame	2	-1	Trad	5.5	1	30	43.8021	-71.8367
Dirtiest Climb	Left of Venus Wall (The Bradley White Wall) > *Rumney > New Hampshire	https://www.mountainproject.com/route/106855895/dirtiest-climb	1	-1	Trad	5.6	2	50	43.8021	-71.8367
Bradley White Route	Left of Venus Wall (The Bradley White Wall) > *Rumney > New Hampshire	https://www.mountainproject.com/route/107337128/bradley-white-route	0	-1	Trad	5.6	1	40	43.8021	-71.8367
Cornered	Left of Venus Wall (The Bradley White Wall) > *Rumney > New Hampshire	https://www.mountainproject.com/route/108177279/cornered	0	-1	Trad	5.6	1	40	43.8021	-71.8367
Gettin' Started	Upper Right > Infinity Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/108916749/gettin-started	3.1	-1	Sport	5.6	1	25	43.80439	-71.82882
Ass Crack	Upper Right > Infinity Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/108916614/ass-crack	1	-1	Trad	5.11	1	40	43.80439	-71.82882
Grass Crack	Upper Right > Infinity Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/108916628/grass-crack	3	-1	Trad	5.11	1	40	43.80439	-71.82882
Gas Crack	Upper Right > Infinity Wall > *Rumney > New Hampshire	https://www.mountainproject.com/route/108916634/gas-crack	2	-1	TR	5.11+	1	40	43.80439	-71.82882
Boo!	Haunted House > *Rumney > New Hampshire	https://www.mountainproject.com/route/107337164/boo	0	-1	Trad	5.6 PG13	1	40	43.8021	-71.8367
Chris Buckley's Arete	The Monolith > *Rumney > New Hampshire	https://www.mountainproject.com/route/107761357/chris-buckleys-arete	3	-1	Sport	5.7	1	100	43.8021	-71.8367
Sasquatch Summer ascent	The Monolith > *Rumney > New Hampshire	https://www.mountainproject.com/route/109525592/sasquatch-summer-ascent	1.2	-1	Sport	5.1	1	100	43.8021	-71.8367
Giimoozaabi (unfinshed)	The Monolith > *Rumney > New Hampshire	https://www.mountainproject.com/route/106941576/giimoozaabi-unfinshed	2	-1	"Sport, Aid"	5.10b/c C0	1	80	43.8021	-71.8367
The Monolith	The Monolith > *Rumney > New Hampshire	https://www.mountainproject.com/route/107761306/the-monolith	1.8	-1	Sport	5.10d	1	80	43.8021	-71.8367
Schwarze Weissnergrat	Höhe Hinterland > *Rumney > New Hampshire	https://www.mountainproject.com/route/107660445/schwarze-weissnergrat	2	-1	Sport	5.8	1	45	43.8021	-71.8367
Der Riss	Höhe Hinterland > *Rumney > New Hampshire	https://www.mountainproject.com/route/107661281/der-riss	2	-1	Trad	5.9+	1	45	43.8021	-71.8367
Hanzel und Gretyl	Höhe Hinterland > *Rumney > New Hampshire	https://www.mountainproject.com/route/107615112/hanzel-und-gretyl	1.8	-1	Trad	5.10a	1	35	43.8021	-71.8367
Höhe Hinterland	Höhe Hinterland > *Rumney > New Hampshire	https://www.mountainproject.com/route/107617020/hohe-hinterland	1.3	-1	Trad	5.10a	4	200	43.8021	-71.8367
Wünderkind	Höhe Hinterland > *Rumney > New Hampshire	https://www.mountainproject.com/route/107632283/wunderkind	4	-1	Sport	5.11c	1	60	43.8021	-71.8367
Hail No	Hail Vader > *Rumney > New Hampshire	https://www.mountainproject.com/route/108096669/hail-no	1.4	-1	Trad	5.2	1	30	43.8021	-71.8367
Hail Yes	Hail Vader > *Rumney > New Hampshire	https://www.mountainproject.com/route/108096647/hail-yes	2	-1	Trad	5.3	1	30	43.8021	-71.8367
Imperial Salute	Hail Vader > *Rumney > New Hampshire	https://www.mountainproject.com/route/108096676/imperial-salute	1.3	-1	Trad	5.4	1	30	43.8021	-71.8367
Double Creature Feature	The Very Nice Crag > *Rumney > New Hampshire	https://www.mountainproject.com/route/109590485/double-creature-feature	1.7	-1	Trad	5.7	1	30	43.80545	-71.84486
Final Frontier	The Very Nice Crag > *Rumney > New Hampshire	https://www.mountainproject.com/route/113099071/final-frontier	1.6	-1	Sport	5.8	1	60	43.80545	-71.84486
Mixed up Crack	The Very Nice Crag > *Rumney > New Hampshire	https://www.mountainproject.com/route/113708824/mixed-up-crack	2	-1	Trad	5.8	1	50	43.80545	-71.84486
Cozened Stone	The Very Nice Crag > *Rumney > New Hampshire	https://www.mountainproject.com/route/108370872/cozened-stone	3.2	-1	Sport	5.9	1	80	43.80545	-71.84486
'Lectra Crack	The Very Nice Crag > *Rumney > New Hampshire	https://www.mountainproject.com/route/108281446/lectra-crack	1.9	-1	Trad	5.9+	1	45	43.80545	-71.84486
Rippopotamus	The Very Nice Crag > *Rumney > New Hampshire	https://www.mountainproject.com/route/113099109/rippopotamus	1.9	-1	Sport	5.9+	1	25	43.80545	-71.84486
Tintinabulation	The Very Nice Crag > *Rumney > New Hampshire	https://www.mountainproject.com/route/113497631/tintinabulation	1.9	-1	Sport	5.10a	1	45	43.80545	-71.84486
Project	The Very Nice Crag > *Rumney > New Hampshire	https://www.mountainproject.com/route/116574906/project	1.5	-1	TR	5.1	1	35	43.80545	-71.84486
The Lord's Prayer	The Very Nice Crag > *Rumney > New Hampshire	https://www.mountainproject.com/route/109590472/the-lords-prayer	2.2	-1	Sport	5.10c	1	40	43.80545	-71.84486
Very Nice Crack	The Very Nice Crag > *Rumney > New Hampshire	https://www.mountainproject.com/route/106119507/very-nice-crack	2.7	-1	Trad	5.10d	1		43.80545	-71.84486
Pretty Good Face	The Very Nice Crag > *Rumney > New Hampshire	https://www.mountainproject.com/route/108417155/pretty-good-face	2	-1	Sport	5.11a	1		43.80545	-71.84486
The Friend Zone	The Very Nice Crag > *Rumney > New Hampshire	https://www.mountainproject.com/route/106887427/the-friend-zone	2.4	-1	Sport	5.11c	1	35	43.80545	-71.84486
After All This Time	The Balcony > *Rumney > New Hampshire	https://www.mountainproject.com/route/110964463/after-all-this-time	3.5	-1	Sport	5.7	1	50	43.80293	-71.83505
Sight Unseen	The Balcony > *Rumney > New Hampshire	https://www.mountainproject.com/route/110964570/sight-unseen	2.4	-1	Sport	5.7	1		43.80293	-71.83505
Always	The Balcony > *Rumney > New Hampshire	https://www.mountainproject.com/route/110964507/always	2	-1	Sport	5.10b	1	50	43.80293	-71.83505
Book of Sins	Small Wall > The Buffalo Corral > *Rumney > New Hampshire	https://www.mountainproject.com/route/113494147/book-of-sins	2.1	-1	Sport	5.5	1	30	43.80307	-71.84859
Night Songs	Small Wall > The Buffalo Corral > *Rumney > New Hampshire	https://www.mountainproject.com/route/113494173/night-songs	2.1	-1	Sport	5.10b/c	1	30	43.80307	-71.84859
Mighty Mouse	Small Wall > The Buffalo Corral > *Rumney > New Hampshire	https://www.mountainproject.com/route/113506703/mighty-mouse	2.2	-1	Sport	5.10c	1	30	43.80307	-71.84859
East West East (aka Unknown Soldier)	Small Wall > The Buffalo Corral > *Rumney > New Hampshire	https://www.mountainproject.com/route/113506716/east-west-east-aka-unknown-soldier	1.8	-1	Sport	5.11b	1		43.80307	-71.84859
Mild Horses	Slab Wall > The Buffalo Corral > *Rumney > New Hampshire	https://www.mountainproject.com/route/113509622/mild-horses	1.9	-1	Sport	5.5	1	50	43.80299	-71.8488
Ghost Pine	Slab Wall > The Buffalo Corral > *Rumney > New Hampshire	https://www.mountainproject.com/route/113509638/ghost-pine	2	-1	Sport	5.6	1	50	43.80299	-71.8488
Bison Burger	Slab Wall > The Buffalo Corral > *Rumney > New Hampshire	https://www.mountainproject.com/route/113509669/bison-burger	2.5	-1	Sport	5.7	1	50	43.80299	-71.8488
Bleached Bones	Slab Wall > The Buffalo Corral > *Rumney > New Hampshire	https://www.mountainproject.com/route/113509707/bleached-bones	2.3	-1	Sport	5.7	1	50	43.80299	-71.8488
Twinkle Toes	Slab Wall > The Buffalo Corral > *Rumney > New Hampshire	https://www.mountainproject.com/route/113509662/twinkle-toes	2	-1	Sport	5.7+	1	50	43.80299	-71.8488
Stampede	Slab Wall > The Buffalo Corral > *Rumney > New Hampshire	https://www.mountainproject.com/route/113509694/stampede	2.4	-1	Sport	5.8	1	50	43.80299	-71.8488
Flaming Arrow	Slab Wall > The Buffalo Corral > *Rumney > New Hampshire	https://www.mountainproject.com/route/113509678/flaming-arrow	2.5	-1	Sport	5.9+	1	50	43.80299	-71.8488
